/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module hac_deskew_dut(clk, rst_n, instr_valid, instr_ready, instr_data, link_tx, link_tx_v, link_tx_r, link_rx, link_rx_v, link_rx_r, hac_val, sac_val, phase_status, delta_t);
  wire _0000_;
  wire _0001_;
  wire _0002_;
  wire _0003_;
  wire _0004_;
  wire _0005_;
  wire _0006_;
  wire _0007_;
  wire _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  input clk;
  wire clk;
  output [15:0] delta_t;
  wire [15:0] delta_t;
  wire \hac_inst.count[0] ;
  wire \hac_inst.count[10] ;
  wire \hac_inst.count[11] ;
  wire \hac_inst.count[12] ;
  wire \hac_inst.count[13] ;
  wire \hac_inst.count[14] ;
  wire \hac_inst.count[15] ;
  wire \hac_inst.count[16] ;
  wire \hac_inst.count[17] ;
  wire \hac_inst.count[18] ;
  wire \hac_inst.count[19] ;
  wire \hac_inst.count[1] ;
  wire \hac_inst.count[20] ;
  wire \hac_inst.count[21] ;
  wire \hac_inst.count[22] ;
  wire \hac_inst.count[23] ;
  wire \hac_inst.count[24] ;
  wire \hac_inst.count[25] ;
  wire \hac_inst.count[26] ;
  wire \hac_inst.count[27] ;
  wire \hac_inst.count[28] ;
  wire \hac_inst.count[29] ;
  wire \hac_inst.count[2] ;
  wire \hac_inst.count[30] ;
  wire \hac_inst.count[31] ;
  wire \hac_inst.count[3] ;
  wire \hac_inst.count[4] ;
  wire \hac_inst.count[5] ;
  wire \hac_inst.count[6] ;
  wire \hac_inst.count[7] ;
  wire \hac_inst.count[8] ;
  wire \hac_inst.count[9] ;
  wire \hac_offset[0] ;
  wire \hac_offset[10] ;
  wire \hac_offset[11] ;
  wire \hac_offset[12] ;
  wire \hac_offset[13] ;
  wire \hac_offset[14] ;
  wire \hac_offset[15] ;
  wire \hac_offset[16] ;
  wire \hac_offset[17] ;
  wire \hac_offset[18] ;
  wire \hac_offset[19] ;
  wire \hac_offset[1] ;
  wire \hac_offset[20] ;
  wire \hac_offset[21] ;
  wire \hac_offset[22] ;
  wire \hac_offset[23] ;
  wire \hac_offset[24] ;
  wire \hac_offset[25] ;
  wire \hac_offset[26] ;
  wire \hac_offset[27] ;
  wire \hac_offset[28] ;
  wire \hac_offset[29] ;
  wire \hac_offset[2] ;
  wire \hac_offset[30] ;
  wire \hac_offset[31] ;
  wire \hac_offset[3] ;
  wire \hac_offset[4] ;
  wire \hac_offset[5] ;
  wire \hac_offset[6] ;
  wire \hac_offset[7] ;
  wire \hac_offset[8] ;
  wire \hac_offset[9] ;
  output [31:0] hac_val;
  wire [31:0] hac_val;
  input [39:0] instr_data;
  wire [39:0] instr_data;
  output instr_ready;
  wire instr_ready;
  input instr_valid;
  wire instr_valid;
  input [47:0] link_rx;
  wire [47:0] link_rx;
  output link_rx_r;
  wire link_rx_r;
  input link_rx_v;
  wire link_rx_v;
  output [47:0] link_tx;
  wire [47:0] link_tx;
  input link_tx_r;
  wire link_tx_r;
  output link_tx_v;
  wire link_tx_v;
  output [7:0] phase_status;
  wire [7:0] phase_status;
  input rst_n;
  wire rst_n;
  output [31:0] sac_val;
  wire [31:0] sac_val;
  sky130_fd_sc_hd__inv_2 _0637_ (
    .A(\hac_inst.count[0] ),
    .Y(_0002_)
  );
  sky130_fd_sc_hd__inv_2 _0638_ (
    .A(sac_val[0]),
    .Y(_0101_)
  );
  sky130_fd_sc_hd__inv_2 _0639_ (
    .A(phase_status[0]),
    .Y(_0102_)
  );
  sky130_fd_sc_hd__inv_2 _0640_ (
    .A(instr_data[17]),
    .Y(_0103_)
  );
  sky130_fd_sc_hd__inv_2 _0641_ (
    .A(\hac_offset[23] ),
    .Y(_0104_)
  );
  sky130_fd_sc_hd__inv_2 _0642_ (
    .A(\hac_inst.count[22] ),
    .Y(_0105_)
  );
  sky130_fd_sc_hd__inv_2 _0643_ (
    .A(\hac_inst.count[15] ),
    .Y(_0106_)
  );
  sky130_fd_sc_hd__inv_2 _0644_ (
    .A(\hac_inst.count[14] ),
    .Y(_0107_)
  );
  sky130_fd_sc_hd__inv_2 _0645_ (
    .A(\hac_inst.count[8] ),
    .Y(_0108_)
  );
  sky130_fd_sc_hd__inv_2 _0646_ (
    .A(\hac_inst.count[7] ),
    .Y(_0109_)
  );
  sky130_fd_sc_hd__inv_2 _0647_ (
    .A(\hac_offset[4] ),
    .Y(_0110_)
  );
  sky130_fd_sc_hd__inv_2 _0648_ (
    .A(\hac_offset[24] ),
    .Y(_0111_)
  );
  sky130_fd_sc_hd__inv_2 _0649_ (
    .A(\hac_inst.count[26] ),
    .Y(_0112_)
  );
  sky130_fd_sc_hd__inv_2 _0650_ (
    .A(\hac_offset[26] ),
    .Y(_0113_)
  );
  sky130_fd_sc_hd__inv_2 _0651_ (
    .A(\hac_offset[29] ),
    .Y(_0114_)
  );
  sky130_fd_sc_hd__inv_2 _0652_ (
    .A(\hac_inst.count[30] ),
    .Y(_0115_)
  );
  sky130_fd_sc_hd__inv_2 _0653_ (
    .A(sac_val[12]),
    .Y(_0116_)
  );
  sky130_fd_sc_hd__inv_2 _0654_ (
    .A(link_rx[12]),
    .Y(_0117_)
  );
  sky130_fd_sc_hd__inv_2 _0655_ (
    .A(link_rx[14]),
    .Y(_0118_)
  );
  sky130_fd_sc_hd__inv_2 _0656_ (
    .A(link_rx[30]),
    .Y(_0119_)
  );
  sky130_fd_sc_hd__inv_2 _0657_ (
    .A(link_rx[31]),
    .Y(_0120_)
  );
  sky130_fd_sc_hd__inv_2 _0658_ (
    .A(link_rx[32]),
    .Y(_0121_)
  );
  sky130_fd_sc_hd__inv_2 _0659_ (
    .A(link_rx[36]),
    .Y(_0122_)
  );
  sky130_fd_sc_hd__nand2b_2 _0660_ (
    .A_N(\hac_inst.count[0] ),
    .B(\hac_offset[0] ),
    .Y(_0123_)
  );
  sky130_fd_sc_hd__or2_2 _0661_ (
    .A(_0002_),
    .B(\hac_offset[0] ),
    .X(_0124_)
  );
  sky130_fd_sc_hd__nand2_2 _0662_ (
    .A(_0123_),
    .B(_0124_),
    .Y(hac_val[0])
  );
  sky130_fd_sc_hd__nand2b_2 _0663_ (
    .A_N(\hac_inst.count[0] ),
    .B(sac_val[0]),
    .Y(_0125_)
  );
  sky130_fd_sc_hd__nand2_2 _0664_ (
    .A(\hac_inst.count[0] ),
    .B(_0101_),
    .Y(_0126_)
  );
  sky130_fd_sc_hd__nand2_2 _0665_ (
    .A(_0125_),
    .B(_0126_),
    .Y(delta_t[0])
  );
  sky130_fd_sc_hd__nand2b_2 _0666_ (
    .A_N(phase_status[5]),
    .B(phase_status[4]),
    .Y(_0001_)
  );
  sky130_fd_sc_hd__nor3_2 _0667_ (
    .A(phase_status[0]),
    .B(phase_status[5]),
    .C(phase_status[4]),
    .Y(_0000_)
  );
  sky130_fd_sc_hd__xnor2_2 _0668_ (
    .A(\hac_inst.count[23] ),
    .B(\hac_offset[23] ),
    .Y(_0127_)
  );
  sky130_fd_sc_hd__nor2_2 _0669_ (
    .A(\hac_offset[22] ),
    .B(_0105_),
    .Y(_0128_)
  );
  sky130_fd_sc_hd__nand2_2 _0670_ (
    .A(\hac_offset[22] ),
    .B(_0105_),
    .Y(_0129_)
  );
  sky130_fd_sc_hd__and2b_2 _0671_ (
    .A_N(_0128_),
    .B(_0129_),
    .X(_0130_)
  );
  sky130_fd_sc_hd__and2b_2 _0672_ (
    .A_N(\hac_inst.count[21] ),
    .B(\hac_offset[21] ),
    .X(_0131_)
  );
  sky130_fd_sc_hd__inv_2 _0673_ (
    .A(_0131_),
    .Y(_0132_)
  );
  sky130_fd_sc_hd__and2b_2 _0674_ (
    .A_N(\hac_offset[21] ),
    .B(\hac_inst.count[21] ),
    .X(_0133_)
  );
  sky130_fd_sc_hd__and2b_2 _0675_ (
    .A_N(\hac_offset[20] ),
    .B(\hac_inst.count[20] ),
    .X(_0134_)
  );
  sky130_fd_sc_hd__o21a_2 _0676_ (
    .A1(_0133_),
    .A2(_0134_),
    .B1(_0132_),
    .X(_0135_)
  );
  sky130_fd_sc_hd__nor2_2 _0677_ (
    .A(_0131_),
    .B(_0133_),
    .Y(_0136_)
  );
  sky130_fd_sc_hd__and2b_2 _0678_ (
    .A_N(\hac_inst.count[20] ),
    .B(\hac_offset[20] ),
    .X(_0137_)
  );
  sky130_fd_sc_hd__nor2_2 _0679_ (
    .A(_0134_),
    .B(_0137_),
    .Y(_0138_)
  );
  sky130_fd_sc_hd__or2_2 _0680_ (
    .A(_0134_),
    .B(_0137_),
    .X(_0139_)
  );
  sky130_fd_sc_hd__and2b_2 _0681_ (
    .A_N(\hac_offset[19] ),
    .B(\hac_inst.count[19] ),
    .X(_0140_)
  );
  sky130_fd_sc_hd__nand2b_2 _0682_ (
    .A_N(\hac_offset[19] ),
    .B(\hac_inst.count[19] ),
    .Y(_0141_)
  );
  sky130_fd_sc_hd__and2b_2 _0683_ (
    .A_N(\hac_inst.count[19] ),
    .B(\hac_offset[19] ),
    .X(_0142_)
  );
  sky130_fd_sc_hd__nand2b_2 _0684_ (
    .A_N(\hac_offset[18] ),
    .B(\hac_inst.count[18] ),
    .Y(_0143_)
  );
  sky130_fd_sc_hd__xnor2_2 _0685_ (
    .A(\hac_offset[18] ),
    .B(\hac_inst.count[18] ),
    .Y(_0144_)
  );
  sky130_fd_sc_hd__inv_2 _0686_ (
    .A(_0144_),
    .Y(_0145_)
  );
  sky130_fd_sc_hd__and2b_2 _0687_ (
    .A_N(\hac_offset[17] ),
    .B(\hac_inst.count[17] ),
    .X(_0146_)
  );
  sky130_fd_sc_hd__nand2b_2 _0688_ (
    .A_N(\hac_offset[17] ),
    .B(\hac_inst.count[17] ),
    .Y(_0147_)
  );
  sky130_fd_sc_hd__and2b_2 _0689_ (
    .A_N(\hac_inst.count[17] ),
    .B(\hac_offset[17] ),
    .X(_0148_)
  );
  sky130_fd_sc_hd__nor2_2 _0690_ (
    .A(_0146_),
    .B(_0148_),
    .Y(_0149_)
  );
  sky130_fd_sc_hd__nand2b_2 _0691_ (
    .A_N(\hac_offset[16] ),
    .B(\hac_inst.count[16] ),
    .Y(_0150_)
  );
  sky130_fd_sc_hd__xnor2_2 _0692_ (
    .A(\hac_offset[16] ),
    .B(\hac_inst.count[16] ),
    .Y(_0151_)
  );
  sky130_fd_sc_hd__inv_2 _0693_ (
    .A(_0151_),
    .Y(_0152_)
  );
  sky130_fd_sc_hd__xnor2_2 _0694_ (
    .A(\hac_offset[15] ),
    .B(\hac_inst.count[15] ),
    .Y(_0153_)
  );
  sky130_fd_sc_hd__nor2_2 _0695_ (
    .A(\hac_offset[14] ),
    .B(_0107_),
    .Y(_0154_)
  );
  sky130_fd_sc_hd__and2_2 _0696_ (
    .A(\hac_offset[14] ),
    .B(_0107_),
    .X(_0155_)
  );
  sky130_fd_sc_hd__nor2_2 _0697_ (
    .A(_0154_),
    .B(_0155_),
    .Y(_0156_)
  );
  sky130_fd_sc_hd__nand2_2 _0698_ (
    .A(_0153_),
    .B(_0156_),
    .Y(_0157_)
  );
  sky130_fd_sc_hd__and2b_2 _0699_ (
    .A_N(\hac_offset[13] ),
    .B(\hac_inst.count[13] ),
    .X(_0158_)
  );
  sky130_fd_sc_hd__nand2b_2 _0700_ (
    .A_N(\hac_inst.count[13] ),
    .B(\hac_offset[13] ),
    .Y(_0159_)
  );
  sky130_fd_sc_hd__and2b_2 _0701_ (
    .A_N(_0158_),
    .B(_0159_),
    .X(_0160_)
  );
  sky130_fd_sc_hd__and2b_2 _0702_ (
    .A_N(\hac_offset[12] ),
    .B(\hac_inst.count[12] ),
    .X(_0161_)
  );
  sky130_fd_sc_hd__and2b_2 _0703_ (
    .A_N(\hac_inst.count[12] ),
    .B(\hac_offset[12] ),
    .X(_0162_)
  );
  sky130_fd_sc_hd__or2_2 _0704_ (
    .A(_0161_),
    .B(_0162_),
    .X(_0163_)
  );
  sky130_fd_sc_hd__or4b_2 _0705_ (
    .A(_0157_),
    .B(_0158_),
    .C(_0163_),
    .D_N(_0159_),
    .X(_0164_)
  );
  sky130_fd_sc_hd__and2b_2 _0706_ (
    .A_N(\hac_offset[11] ),
    .B(\hac_inst.count[11] ),
    .X(_0165_)
  );
  sky130_fd_sc_hd__and2b_2 _0707_ (
    .A_N(\hac_inst.count[11] ),
    .B(\hac_offset[11] ),
    .X(_0166_)
  );
  sky130_fd_sc_hd__nand2b_2 _0708_ (
    .A_N(\hac_offset[10] ),
    .B(\hac_inst.count[10] ),
    .Y(_0167_)
  );
  sky130_fd_sc_hd__o21ba_2 _0709_ (
    .A1(_0166_),
    .A2(_0167_),
    .B1_N(_0165_),
    .X(_0168_)
  );
  sky130_fd_sc_hd__nor2_2 _0710_ (
    .A(_0165_),
    .B(_0166_),
    .Y(_0169_)
  );
  sky130_fd_sc_hd__nand2b_2 _0711_ (
    .A_N(\hac_inst.count[10] ),
    .B(\hac_offset[10] ),
    .Y(_0170_)
  );
  sky130_fd_sc_hd__and2_2 _0712_ (
    .A(_0167_),
    .B(_0170_),
    .X(_0171_)
  );
  sky130_fd_sc_hd__nand2_2 _0713_ (
    .A(_0167_),
    .B(_0170_),
    .Y(_0172_)
  );
  sky130_fd_sc_hd__and2b_2 _0714_ (
    .A_N(\hac_inst.count[9] ),
    .B(\hac_offset[9] ),
    .X(_0173_)
  );
  sky130_fd_sc_hd__nand2b_2 _0715_ (
    .A_N(\hac_offset[6] ),
    .B(\hac_inst.count[6] ),
    .Y(_0174_)
  );
  sky130_fd_sc_hd__nand2b_2 _0716_ (
    .A_N(\hac_inst.count[6] ),
    .B(\hac_offset[6] ),
    .Y(_0175_)
  );
  sky130_fd_sc_hd__nand2_2 _0717_ (
    .A(_0174_),
    .B(_0175_),
    .Y(_0176_)
  );
  sky130_fd_sc_hd__xor2_2 _0718_ (
    .A(\hac_offset[7] ),
    .B(\hac_inst.count[7] ),
    .X(_0177_)
  );
  sky130_fd_sc_hd__and2b_2 _0719_ (
    .A_N(\hac_inst.count[5] ),
    .B(\hac_offset[5] ),
    .X(_0178_)
  );
  sky130_fd_sc_hd__and2b_2 _0720_ (
    .A_N(\hac_offset[5] ),
    .B(\hac_inst.count[5] ),
    .X(_0179_)
  );
  sky130_fd_sc_hd__a21oi_2 _0721_ (
    .A1(_0110_),
    .A2(\hac_inst.count[4] ),
    .B1(_0179_),
    .Y(_0180_)
  );
  sky130_fd_sc_hd__and2b_2 _0722_ (
    .A_N(\hac_offset[3] ),
    .B(\hac_inst.count[3] ),
    .X(_0181_)
  );
  sky130_fd_sc_hd__and2b_2 _0723_ (
    .A_N(\hac_offset[2] ),
    .B(\hac_inst.count[2] ),
    .X(_0182_)
  );
  sky130_fd_sc_hd__nand2b_2 _0724_ (
    .A_N(\hac_inst.count[2] ),
    .B(\hac_offset[2] ),
    .Y(_0183_)
  );
  sky130_fd_sc_hd__nand2b_2 _0725_ (
    .A_N(_0182_),
    .B(_0183_),
    .Y(_0184_)
  );
  sky130_fd_sc_hd__and2b_2 _0726_ (
    .A_N(\hac_offset[1] ),
    .B(\hac_inst.count[1] ),
    .X(_0185_)
  );
  sky130_fd_sc_hd__xnor2_2 _0727_ (
    .A(\hac_offset[1] ),
    .B(\hac_inst.count[1] ),
    .Y(_0186_)
  );
  sky130_fd_sc_hd__a21o_2 _0728_ (
    .A1(_0123_),
    .A2(_0186_),
    .B1(_0185_),
    .X(_0187_)
  );
  sky130_fd_sc_hd__a21o_2 _0729_ (
    .A1(_0183_),
    .A2(_0187_),
    .B1(_0182_),
    .X(_0188_)
  );
  sky130_fd_sc_hd__nand2b_2 _0730_ (
    .A_N(\hac_inst.count[3] ),
    .B(\hac_offset[3] ),
    .Y(_0189_)
  );
  sky130_fd_sc_hd__nand2b_2 _0731_ (
    .A_N(_0181_),
    .B(_0189_),
    .Y(_0190_)
  );
  sky130_fd_sc_hd__a21o_2 _0732_ (
    .A1(_0188_),
    .A2(_0189_),
    .B1(_0181_),
    .X(_0191_)
  );
  sky130_fd_sc_hd__xnor2_2 _0733_ (
    .A(\hac_offset[4] ),
    .B(\hac_inst.count[4] ),
    .Y(_0192_)
  );
  sky130_fd_sc_hd__nand2_2 _0734_ (
    .A(_0191_),
    .B(_0192_),
    .Y(_0193_)
  );
  sky130_fd_sc_hd__a21o_2 _0735_ (
    .A1(_0180_),
    .A2(_0193_),
    .B1(_0178_),
    .X(_0194_)
  );
  sky130_fd_sc_hd__or4_2 _0736_ (
    .A(_0176_),
    .B(_0177_),
    .C(_0178_),
    .D(_0180_),
    .X(_0195_)
  );
  sky130_fd_sc_hd__nor2_2 _0737_ (
    .A(_0178_),
    .B(_0179_),
    .Y(_0196_)
  );
  sky130_fd_sc_hd__and4bb_2 _0738_ (
    .A_N(_0176_),
    .B_N(_0177_),
    .C(_0192_),
    .D(_0196_),
    .X(_0197_)
  );
  sky130_fd_sc_hd__a21boi_2 _0739_ (
    .A1(_0191_),
    .A2(_0197_),
    .B1_N(_0195_),
    .Y(_0198_)
  );
  sky130_fd_sc_hd__a21o_2 _0740_ (
    .A1(\hac_offset[7] ),
    .A2(_0109_),
    .B1(_0174_),
    .X(_0199_)
  );
  sky130_fd_sc_hd__o21a_2 _0741_ (
    .A1(\hac_offset[7] ),
    .A2(_0109_),
    .B1(_0199_),
    .X(_0200_)
  );
  sky130_fd_sc_hd__and2_2 _0742_ (
    .A(_0198_),
    .B(_0200_),
    .X(_0201_)
  );
  sky130_fd_sc_hd__or2_2 _0743_ (
    .A(\hac_offset[8] ),
    .B(_0108_),
    .X(_0202_)
  );
  sky130_fd_sc_hd__xnor2_2 _0744_ (
    .A(\hac_offset[8] ),
    .B(\hac_inst.count[8] ),
    .Y(_0203_)
  );
  sky130_fd_sc_hd__nand2b_2 _0745_ (
    .A_N(_0201_),
    .B(_0203_),
    .Y(_0204_)
  );
  sky130_fd_sc_hd__nand2b_2 _0746_ (
    .A_N(\hac_offset[9] ),
    .B(\hac_inst.count[9] ),
    .Y(_0205_)
  );
  sky130_fd_sc_hd__o31a_2 _0747_ (
    .A1(\hac_offset[8] ),
    .A2(_0108_),
    .A3(_0173_),
    .B1(_0205_),
    .X(_0206_)
  );
  sky130_fd_sc_hd__and2b_2 _0748_ (
    .A_N(_0173_),
    .B(_0205_),
    .X(_0207_)
  );
  sky130_fd_sc_hd__a31o_2 _0749_ (
    .A1(_0202_),
    .A2(_0204_),
    .A3(_0205_),
    .B1(_0173_),
    .X(_0208_)
  );
  sky130_fd_sc_hd__o41a_2 _0750_ (
    .A1(_0165_),
    .A2(_0166_),
    .A3(_0172_),
    .A4(_0206_),
    .B1(_0168_),
    .X(_0209_)
  );
  sky130_fd_sc_hd__and4_2 _0751_ (
    .A(_0169_),
    .B(_0171_),
    .C(_0203_),
    .D(_0207_),
    .X(_0210_)
  );
  sky130_fd_sc_hd__a21bo_2 _0752_ (
    .A1(_0198_),
    .A2(_0200_),
    .B1_N(_0210_),
    .X(_0211_)
  );
  sky130_fd_sc_hd__a21o_2 _0753_ (
    .A1(_0209_),
    .A2(_0211_),
    .B1(_0164_),
    .X(_0212_)
  );
  sky130_fd_sc_hd__a21o_2 _0754_ (
    .A1(\hac_offset[15] ),
    .A2(_0106_),
    .B1(_0107_),
    .X(_0213_)
  );
  sky130_fd_sc_hd__or2_2 _0755_ (
    .A(_0158_),
    .B(_0161_),
    .X(_0214_)
  );
  sky130_fd_sc_hd__nand3b_2 _0756_ (
    .A_N(_0157_),
    .B(_0159_),
    .C(_0214_),
    .Y(_0215_)
  );
  sky130_fd_sc_hd__o221a_2 _0757_ (
    .A1(\hac_offset[15] ),
    .A2(_0106_),
    .B1(\hac_offset[14] ),
    .B2(_0213_),
    .C1(_0215_),
    .X(_0216_)
  );
  sky130_fd_sc_hd__nand2_2 _0758_ (
    .A(_0212_),
    .B(_0216_),
    .Y(_0217_)
  );
  sky130_fd_sc_hd__a21o_2 _0759_ (
    .A1(_0212_),
    .A2(_0216_),
    .B1(_0152_),
    .X(_0218_)
  );
  sky130_fd_sc_hd__a31o_2 _0760_ (
    .A1(_0147_),
    .A2(_0150_),
    .A3(_0218_),
    .B1(_0148_),
    .X(_0219_)
  );
  sky130_fd_sc_hd__a311o_2 _0761_ (
    .A1(_0147_),
    .A2(_0150_),
    .A3(_0218_),
    .B1(_0148_),
    .C1(_0145_),
    .X(_0220_)
  );
  sky130_fd_sc_hd__a31o_2 _0762_ (
    .A1(_0141_),
    .A2(_0143_),
    .A3(_0220_),
    .B1(_0142_),
    .X(_0221_)
  );
  sky130_fd_sc_hd__a311oi_2 _0763_ (
    .A1(_0141_),
    .A2(_0143_),
    .A3(_0220_),
    .B1(_0142_),
    .C1(_0139_),
    .Y(_0222_)
  );
  sky130_fd_sc_hd__o311a_2 _0764_ (
    .A1(_0133_),
    .A2(_0134_),
    .A3(_0222_),
    .B1(_0132_),
    .C1(_0130_),
    .X(_0223_)
  );
  sky130_fd_sc_hd__nor2_2 _0765_ (
    .A(_0128_),
    .B(_0223_),
    .Y(_0224_)
  );
  sky130_fd_sc_hd__xnor2_2 _0766_ (
    .A(_0127_),
    .B(_0224_),
    .Y(hac_val[23])
  );
  sky130_fd_sc_hd__xor2_2 _0767_ (
    .A(\hac_inst.count[24] ),
    .B(\hac_offset[24] ),
    .X(_0225_)
  );
  sky130_fd_sc_hd__nand4_2 _0768_ (
    .A(_0127_),
    .B(_0130_),
    .C(_0136_),
    .D(_0138_),
    .Y(_0226_)
  );
  sky130_fd_sc_hd__or4_2 _0769_ (
    .A(_0140_),
    .B(_0142_),
    .C(_0145_),
    .D(_0226_),
    .X(_0227_)
  );
  sky130_fd_sc_hd__o221a_2 _0770_ (
    .A1(\hac_inst.count[23] ),
    .A2(_0104_),
    .B1(_0128_),
    .B2(_0135_),
    .C1(_0129_),
    .X(_0228_)
  );
  sky130_fd_sc_hd__a211o_2 _0771_ (
    .A1(_0141_),
    .A2(_0143_),
    .B1(_0226_),
    .C1(_0142_),
    .X(_0229_)
  );
  sky130_fd_sc_hd__a211o_2 _0772_ (
    .A1(_0147_),
    .A2(_0150_),
    .B1(_0227_),
    .C1(_0148_),
    .X(_0230_)
  );
  sky130_fd_sc_hd__nand2_2 _0773_ (
    .A(_0229_),
    .B(_0230_),
    .Y(_0231_)
  );
  sky130_fd_sc_hd__a211oi_2 _0774_ (
    .A1(\hac_inst.count[23] ),
    .A2(_0104_),
    .B1(_0228_),
    .C1(_0231_),
    .Y(_0232_)
  );
  sky130_fd_sc_hd__nand2_2 _0775_ (
    .A(_0149_),
    .B(_0151_),
    .Y(_0233_)
  );
  sky130_fd_sc_hd__a211o_2 _0776_ (
    .A1(_0212_),
    .A2(_0216_),
    .B1(_0227_),
    .C1(_0233_),
    .X(_0234_)
  );
  sky130_fd_sc_hd__nand2_2 _0777_ (
    .A(_0232_),
    .B(_0234_),
    .Y(_0235_)
  );
  sky130_fd_sc_hd__a21oi_2 _0778_ (
    .A1(_0232_),
    .A2(_0234_),
    .B1(_0225_),
    .Y(_0236_)
  );
  sky130_fd_sc_hd__and3_2 _0779_ (
    .A(_0225_),
    .B(_0232_),
    .C(_0234_),
    .X(_0237_)
  );
  sky130_fd_sc_hd__nor2_2 _0780_ (
    .A(_0236_),
    .B(_0237_),
    .Y(hac_val[24])
  );
  sky130_fd_sc_hd__and2b_2 _0781_ (
    .A_N(\hac_inst.count[25] ),
    .B(\hac_offset[25] ),
    .X(_0238_)
  );
  sky130_fd_sc_hd__and2b_2 _0782_ (
    .A_N(\hac_offset[25] ),
    .B(\hac_inst.count[25] ),
    .X(_0239_)
  );
  sky130_fd_sc_hd__nor2_2 _0783_ (
    .A(_0238_),
    .B(_0239_),
    .Y(_0240_)
  );
  sky130_fd_sc_hd__a21o_2 _0784_ (
    .A1(\hac_inst.count[24] ),
    .A2(_0111_),
    .B1(_0236_),
    .X(_0241_)
  );
  sky130_fd_sc_hd__xor2_2 _0785_ (
    .A(_0240_),
    .B(_0241_),
    .X(hac_val[25])
  );
  sky130_fd_sc_hd__xnor2_2 _0786_ (
    .A(\hac_inst.count[26] ),
    .B(\hac_offset[26] ),
    .Y(_0242_)
  );
  sky130_fd_sc_hd__and2b_2 _0787_ (
    .A_N(_0225_),
    .B(_0240_),
    .X(_0243_)
  );
  sky130_fd_sc_hd__nor2_2 _0788_ (
    .A(\hac_offset[24] ),
    .B(_0238_),
    .Y(_0244_)
  );
  sky130_fd_sc_hd__a21o_2 _0789_ (
    .A1(\hac_inst.count[24] ),
    .A2(_0244_),
    .B1(_0239_),
    .X(_0245_)
  );
  sky130_fd_sc_hd__a21oi_2 _0790_ (
    .A1(_0235_),
    .A2(_0243_),
    .B1(_0245_),
    .Y(_0246_)
  );
  sky130_fd_sc_hd__and2b_2 _0791_ (
    .A_N(_0246_),
    .B(_0242_),
    .X(_0247_)
  );
  sky130_fd_sc_hd__and2b_2 _0792_ (
    .A_N(_0242_),
    .B(_0246_),
    .X(_0248_)
  );
  sky130_fd_sc_hd__nor2_2 _0793_ (
    .A(_0247_),
    .B(_0248_),
    .Y(hac_val[26])
  );
  sky130_fd_sc_hd__and2b_2 _0794_ (
    .A_N(\hac_inst.count[27] ),
    .B(\hac_offset[27] ),
    .X(_0249_)
  );
  sky130_fd_sc_hd__nand2b_2 _0795_ (
    .A_N(\hac_inst.count[27] ),
    .B(\hac_offset[27] ),
    .Y(_0250_)
  );
  sky130_fd_sc_hd__and2b_2 _0796_ (
    .A_N(\hac_offset[27] ),
    .B(\hac_inst.count[27] ),
    .X(_0251_)
  );
  sky130_fd_sc_hd__nor2_2 _0797_ (
    .A(_0249_),
    .B(_0251_),
    .Y(_0252_)
  );
  sky130_fd_sc_hd__a21oi_2 _0798_ (
    .A1(\hac_inst.count[26] ),
    .A2(_0113_),
    .B1(_0247_),
    .Y(_0253_)
  );
  sky130_fd_sc_hd__xnor2_2 _0799_ (
    .A(_0252_),
    .B(_0253_),
    .Y(hac_val[27])
  );
  sky130_fd_sc_hd__nand2b_2 _0800_ (
    .A_N(\hac_inst.count[28] ),
    .B(\hac_offset[28] ),
    .Y(_0254_)
  );
  sky130_fd_sc_hd__and2b_2 _0801_ (
    .A_N(\hac_offset[28] ),
    .B(\hac_inst.count[28] ),
    .X(_0255_)
  );
  sky130_fd_sc_hd__nand2b_2 _0802_ (
    .A_N(\hac_offset[28] ),
    .B(\hac_inst.count[28] ),
    .Y(_0256_)
  );
  sky130_fd_sc_hd__nand2_2 _0803_ (
    .A(_0254_),
    .B(_0256_),
    .Y(_0257_)
  );
  sky130_fd_sc_hd__a31o_2 _0804_ (
    .A1(\hac_inst.count[26] ),
    .A2(_0113_),
    .A3(_0250_),
    .B1(_0251_),
    .X(_0258_)
  );
  sky130_fd_sc_hd__and2_2 _0805_ (
    .A(_0242_),
    .B(_0252_),
    .X(_0259_)
  );
  sky130_fd_sc_hd__nand2_2 _0806_ (
    .A(_0243_),
    .B(_0259_),
    .Y(_0260_)
  );
  sky130_fd_sc_hd__a21oi_2 _0807_ (
    .A1(_0232_),
    .A2(_0234_),
    .B1(_0260_),
    .Y(_0261_)
  );
  sky130_fd_sc_hd__a211o_2 _0808_ (
    .A1(_0245_),
    .A2(_0259_),
    .B1(_0261_),
    .C1(_0258_),
    .X(_0262_)
  );
  sky130_fd_sc_hd__xnor2_2 _0809_ (
    .A(_0257_),
    .B(_0262_),
    .Y(hac_val[28])
  );
  sky130_fd_sc_hd__nor2_2 _0810_ (
    .A(\hac_inst.count[29] ),
    .B(_0114_),
    .Y(_0263_)
  );
  sky130_fd_sc_hd__and2_2 _0811_ (
    .A(\hac_inst.count[29] ),
    .B(_0114_),
    .X(_0264_)
  );
  sky130_fd_sc_hd__or2_2 _0812_ (
    .A(_0263_),
    .B(_0264_),
    .X(_0265_)
  );
  sky130_fd_sc_hd__a21o_2 _0813_ (
    .A1(_0254_),
    .A2(_0262_),
    .B1(_0255_),
    .X(_0266_)
  );
  sky130_fd_sc_hd__xnor2_2 _0814_ (
    .A(_0265_),
    .B(_0266_),
    .Y(hac_val[29])
  );
  sky130_fd_sc_hd__or2_2 _0815_ (
    .A(_0115_),
    .B(\hac_offset[30] ),
    .X(_0267_)
  );
  sky130_fd_sc_hd__nand2_2 _0816_ (
    .A(_0115_),
    .B(\hac_offset[30] ),
    .Y(_0268_)
  );
  sky130_fd_sc_hd__nand2_2 _0817_ (
    .A(_0267_),
    .B(_0268_),
    .Y(_0269_)
  );
  sky130_fd_sc_hd__a211oi_2 _0818_ (
    .A1(_0254_),
    .A2(_0262_),
    .B1(_0264_),
    .C1(_0255_),
    .Y(_0270_)
  );
  sky130_fd_sc_hd__nor2_2 _0819_ (
    .A(_0263_),
    .B(_0270_),
    .Y(_0271_)
  );
  sky130_fd_sc_hd__xnor2_2 _0820_ (
    .A(_0269_),
    .B(_0271_),
    .Y(hac_val[30])
  );
  sky130_fd_sc_hd__o31a_2 _0821_ (
    .A1(_0263_),
    .A2(_0269_),
    .A3(_0270_),
    .B1(_0267_),
    .X(_0272_)
  );
  sky130_fd_sc_hd__xnor2_2 _0822_ (
    .A(\hac_inst.count[31] ),
    .B(\hac_offset[31] ),
    .Y(_0273_)
  );
  sky130_fd_sc_hd__xnor2_2 _0823_ (
    .A(_0272_),
    .B(_0273_),
    .Y(hac_val[31])
  );
  sky130_fd_sc_hd__and2b_2 _0824_ (
    .A_N(sac_val[1]),
    .B(\hac_inst.count[1] ),
    .X(_0274_)
  );
  sky130_fd_sc_hd__xnor2_2 _0825_ (
    .A(\hac_inst.count[1] ),
    .B(sac_val[1]),
    .Y(_0275_)
  );
  sky130_fd_sc_hd__xor2_2 _0826_ (
    .A(_0125_),
    .B(_0275_),
    .X(delta_t[1])
  );
  sky130_fd_sc_hd__and2b_2 _0827_ (
    .A_N(sac_val[2]),
    .B(\hac_inst.count[2] ),
    .X(_0276_)
  );
  sky130_fd_sc_hd__nand2b_2 _0828_ (
    .A_N(\hac_inst.count[2] ),
    .B(sac_val[2]),
    .Y(_0277_)
  );
  sky130_fd_sc_hd__nand2b_2 _0829_ (
    .A_N(_0276_),
    .B(_0277_),
    .Y(_0278_)
  );
  sky130_fd_sc_hd__a21o_2 _0830_ (
    .A1(_0125_),
    .A2(_0275_),
    .B1(_0274_),
    .X(_0279_)
  );
  sky130_fd_sc_hd__xnor2_2 _0831_ (
    .A(_0278_),
    .B(_0279_),
    .Y(delta_t[2])
  );
  sky130_fd_sc_hd__and2b_2 _0832_ (
    .A_N(sac_val[3]),
    .B(\hac_inst.count[3] ),
    .X(_0280_)
  );
  sky130_fd_sc_hd__and2b_2 _0833_ (
    .A_N(\hac_inst.count[3] ),
    .B(sac_val[3]),
    .X(_0281_)
  );
  sky130_fd_sc_hd__nor2_2 _0834_ (
    .A(_0280_),
    .B(_0281_),
    .Y(_0282_)
  );
  sky130_fd_sc_hd__a21o_2 _0835_ (
    .A1(_0277_),
    .A2(_0279_),
    .B1(_0276_),
    .X(_0283_)
  );
  sky130_fd_sc_hd__xor2_2 _0836_ (
    .A(_0282_),
    .B(_0283_),
    .X(delta_t[3])
  );
  sky130_fd_sc_hd__a21o_2 _0837_ (
    .A1(_0282_),
    .A2(_0283_),
    .B1(_0280_),
    .X(_0284_)
  );
  sky130_fd_sc_hd__and2b_2 _0838_ (
    .A_N(\hac_inst.count[4] ),
    .B(sac_val[4]),
    .X(_0285_)
  );
  sky130_fd_sc_hd__and2b_2 _0839_ (
    .A_N(sac_val[4]),
    .B(\hac_inst.count[4] ),
    .X(_0286_)
  );
  sky130_fd_sc_hd__nor2_2 _0840_ (
    .A(_0285_),
    .B(_0286_),
    .Y(_0287_)
  );
  sky130_fd_sc_hd__xor2_2 _0841_ (
    .A(_0284_),
    .B(_0287_),
    .X(delta_t[4])
  );
  sky130_fd_sc_hd__and2b_2 _0842_ (
    .A_N(\hac_inst.count[5] ),
    .B(sac_val[5]),
    .X(_0288_)
  );
  sky130_fd_sc_hd__inv_2 _0843_ (
    .A(_0288_),
    .Y(_0289_)
  );
  sky130_fd_sc_hd__and2b_2 _0844_ (
    .A_N(sac_val[5]),
    .B(\hac_inst.count[5] ),
    .X(_0290_)
  );
  sky130_fd_sc_hd__nor2_2 _0845_ (
    .A(_0288_),
    .B(_0290_),
    .Y(_0291_)
  );
  sky130_fd_sc_hd__a21oi_2 _0846_ (
    .A1(_0284_),
    .A2(_0287_),
    .B1(_0286_),
    .Y(_0292_)
  );
  sky130_fd_sc_hd__xnor2_2 _0847_ (
    .A(_0291_),
    .B(_0292_),
    .Y(delta_t[5])
  );
  sky130_fd_sc_hd__and2b_2 _0848_ (
    .A_N(sac_val[6]),
    .B(\hac_inst.count[6] ),
    .X(_0293_)
  );
  sky130_fd_sc_hd__nand2b_2 _0849_ (
    .A_N(\hac_inst.count[6] ),
    .B(sac_val[6]),
    .Y(_0294_)
  );
  sky130_fd_sc_hd__nand2b_2 _0850_ (
    .A_N(_0293_),
    .B(_0294_),
    .Y(_0295_)
  );
  sky130_fd_sc_hd__a211o_2 _0851_ (
    .A1(_0284_),
    .A2(_0287_),
    .B1(_0290_),
    .C1(_0286_),
    .X(_0296_)
  );
  sky130_fd_sc_hd__and2_2 _0852_ (
    .A(_0289_),
    .B(_0296_),
    .X(_0297_)
  );
  sky130_fd_sc_hd__xnor2_2 _0853_ (
    .A(_0295_),
    .B(_0297_),
    .Y(delta_t[6])
  );
  sky130_fd_sc_hd__nor2_2 _0854_ (
    .A(_0109_),
    .B(sac_val[7]),
    .Y(_0298_)
  );
  sky130_fd_sc_hd__and2_2 _0855_ (
    .A(_0109_),
    .B(sac_val[7]),
    .X(_0299_)
  );
  sky130_fd_sc_hd__nor2_2 _0856_ (
    .A(_0298_),
    .B(_0299_),
    .Y(_0300_)
  );
  sky130_fd_sc_hd__a31o_2 _0857_ (
    .A1(_0289_),
    .A2(_0294_),
    .A3(_0296_),
    .B1(_0293_),
    .X(_0301_)
  );
  sky130_fd_sc_hd__xor2_2 _0858_ (
    .A(_0300_),
    .B(_0301_),
    .X(delta_t[7])
  );
  sky130_fd_sc_hd__a21oi_2 _0859_ (
    .A1(_0300_),
    .A2(_0301_),
    .B1(_0298_),
    .Y(_0302_)
  );
  sky130_fd_sc_hd__and2_2 _0860_ (
    .A(_0108_),
    .B(sac_val[8]),
    .X(_0303_)
  );
  sky130_fd_sc_hd__nor2_2 _0861_ (
    .A(_0108_),
    .B(sac_val[8]),
    .Y(_0304_)
  );
  sky130_fd_sc_hd__nor2_2 _0862_ (
    .A(_0303_),
    .B(_0304_),
    .Y(_0305_)
  );
  sky130_fd_sc_hd__inv_2 _0863_ (
    .A(_0305_),
    .Y(_0306_)
  );
  sky130_fd_sc_hd__or2_2 _0864_ (
    .A(_0302_),
    .B(_0306_),
    .X(_0307_)
  );
  sky130_fd_sc_hd__xnor2_2 _0865_ (
    .A(_0302_),
    .B(_0305_),
    .Y(delta_t[8])
  );
  sky130_fd_sc_hd__and2b_2 _0866_ (
    .A_N(\hac_inst.count[9] ),
    .B(sac_val[9]),
    .X(_0308_)
  );
  sky130_fd_sc_hd__and2b_2 _0867_ (
    .A_N(sac_val[9]),
    .B(\hac_inst.count[9] ),
    .X(_0309_)
  );
  sky130_fd_sc_hd__nor2_2 _0868_ (
    .A(_0308_),
    .B(_0309_),
    .Y(_0310_)
  );
  sky130_fd_sc_hd__and2b_2 _0869_ (
    .A_N(_0304_),
    .B(_0307_),
    .X(_0311_)
  );
  sky130_fd_sc_hd__xnor2_2 _0870_ (
    .A(_0310_),
    .B(_0311_),
    .Y(delta_t[9])
  );
  sky130_fd_sc_hd__nand2b_2 _0871_ (
    .A_N(\hac_inst.count[10] ),
    .B(sac_val[10]),
    .Y(_0312_)
  );
  sky130_fd_sc_hd__and2b_2 _0872_ (
    .A_N(sac_val[10]),
    .B(\hac_inst.count[10] ),
    .X(_0313_)
  );
  sky130_fd_sc_hd__nand2b_2 _0873_ (
    .A_N(sac_val[10]),
    .B(\hac_inst.count[10] ),
    .Y(_0314_)
  );
  sky130_fd_sc_hd__nand2_2 _0874_ (
    .A(_0312_),
    .B(_0314_),
    .Y(_0315_)
  );
  sky130_fd_sc_hd__nor2_2 _0875_ (
    .A(_0304_),
    .B(_0309_),
    .Y(_0316_)
  );
  sky130_fd_sc_hd__a21oi_2 _0876_ (
    .A1(_0307_),
    .A2(_0316_),
    .B1(_0308_),
    .Y(_0317_)
  );
  sky130_fd_sc_hd__xnor2_2 _0877_ (
    .A(_0315_),
    .B(_0317_),
    .Y(delta_t[10])
  );
  sky130_fd_sc_hd__and2b_2 _0878_ (
    .A_N(\hac_inst.count[11] ),
    .B(sac_val[11]),
    .X(_0318_)
  );
  sky130_fd_sc_hd__and2b_2 _0879_ (
    .A_N(sac_val[11]),
    .B(\hac_inst.count[11] ),
    .X(_0319_)
  );
  sky130_fd_sc_hd__nor2_2 _0880_ (
    .A(_0318_),
    .B(_0319_),
    .Y(_0320_)
  );
  sky130_fd_sc_hd__a21oi_2 _0881_ (
    .A1(_0312_),
    .A2(_0317_),
    .B1(_0313_),
    .Y(_0321_)
  );
  sky130_fd_sc_hd__xnor2_2 _0882_ (
    .A(_0320_),
    .B(_0321_),
    .Y(delta_t[11])
  );
  sky130_fd_sc_hd__xor2_2 _0883_ (
    .A(\hac_inst.count[12] ),
    .B(sac_val[12]),
    .X(_0322_)
  );
  sky130_fd_sc_hd__o21bai_2 _0884_ (
    .A1(_0313_),
    .A2(_0319_),
    .B1_N(_0318_),
    .Y(_0323_)
  );
  sky130_fd_sc_hd__or4b_2 _0885_ (
    .A(_0308_),
    .B(_0315_),
    .C(_0316_),
    .D_N(_0320_),
    .X(_0324_)
  );
  sky130_fd_sc_hd__or4b_2 _0886_ (
    .A(_0308_),
    .B(_0309_),
    .C(_0315_),
    .D_N(_0320_),
    .X(_0325_)
  );
  sky130_fd_sc_hd__o31a_2 _0887_ (
    .A1(_0302_),
    .A2(_0306_),
    .A3(_0325_),
    .B1(_0324_),
    .X(_0326_)
  );
  sky130_fd_sc_hd__a21oi_2 _0888_ (
    .A1(_0323_),
    .A2(_0326_),
    .B1(_0322_),
    .Y(_0327_)
  );
  sky130_fd_sc_hd__and3_2 _0889_ (
    .A(_0322_),
    .B(_0323_),
    .C(_0326_),
    .X(_0328_)
  );
  sky130_fd_sc_hd__nor2_2 _0890_ (
    .A(_0327_),
    .B(_0328_),
    .Y(delta_t[12])
  );
  sky130_fd_sc_hd__and2b_2 _0891_ (
    .A_N(\hac_inst.count[13] ),
    .B(sac_val[13]),
    .X(_0329_)
  );
  sky130_fd_sc_hd__nand2b_2 _0892_ (
    .A_N(sac_val[13]),
    .B(\hac_inst.count[13] ),
    .Y(_0330_)
  );
  sky130_fd_sc_hd__and2b_2 _0893_ (
    .A_N(_0329_),
    .B(_0330_),
    .X(_0331_)
  );
  sky130_fd_sc_hd__a21oi_2 _0894_ (
    .A1(\hac_inst.count[12] ),
    .A2(_0116_),
    .B1(_0327_),
    .Y(_0332_)
  );
  sky130_fd_sc_hd__xnor2_2 _0895_ (
    .A(_0331_),
    .B(_0332_),
    .Y(delta_t[13])
  );
  sky130_fd_sc_hd__xor2_2 _0896_ (
    .A(\hac_inst.count[14] ),
    .B(sac_val[14]),
    .X(_0333_)
  );
  sky130_fd_sc_hd__a21o_2 _0897_ (
    .A1(_0330_),
    .A2(_0332_),
    .B1(_0329_),
    .X(_0334_)
  );
  sky130_fd_sc_hd__a211o_2 _0898_ (
    .A1(_0330_),
    .A2(_0332_),
    .B1(_0333_),
    .C1(_0329_),
    .X(_0335_)
  );
  sky130_fd_sc_hd__nand2_2 _0899_ (
    .A(_0333_),
    .B(_0334_),
    .Y(_0336_)
  );
  sky130_fd_sc_hd__and2_2 _0900_ (
    .A(_0335_),
    .B(_0336_),
    .X(delta_t[14])
  );
  sky130_fd_sc_hd__o21a_2 _0901_ (
    .A1(_0107_),
    .A2(sac_val[14]),
    .B1(_0335_),
    .X(_0337_)
  );
  sky130_fd_sc_hd__xnor2_2 _0902_ (
    .A(\hac_inst.count[15] ),
    .B(sac_val[15]),
    .Y(_0338_)
  );
  sky130_fd_sc_hd__xnor2_2 _0903_ (
    .A(_0337_),
    .B(_0338_),
    .Y(delta_t[15])
  );
  sky130_fd_sc_hd__xor2_2 _0904_ (
    .A(\hac_inst.count[0] ),
    .B(\hac_inst.count[1] ),
    .X(_0013_)
  );
  sky130_fd_sc_hd__and3_2 _0905_ (
    .A(\hac_inst.count[0] ),
    .B(\hac_inst.count[2] ),
    .C(\hac_inst.count[1] ),
    .X(_0339_)
  );
  sky130_fd_sc_hd__a21oi_2 _0906_ (
    .A1(\hac_inst.count[0] ),
    .A2(\hac_inst.count[1] ),
    .B1(\hac_inst.count[2] ),
    .Y(_0340_)
  );
  sky130_fd_sc_hd__nor2_2 _0907_ (
    .A(_0339_),
    .B(_0340_),
    .Y(_0024_)
  );
  sky130_fd_sc_hd__and4_2 _0908_ (
    .A(\hac_inst.count[0] ),
    .B(\hac_inst.count[3] ),
    .C(\hac_inst.count[2] ),
    .D(\hac_inst.count[1] ),
    .X(_0341_)
  );
  sky130_fd_sc_hd__nor2_2 _0909_ (
    .A(\hac_inst.count[3] ),
    .B(_0339_),
    .Y(_0342_)
  );
  sky130_fd_sc_hd__nor2_2 _0910_ (
    .A(_0341_),
    .B(_0342_),
    .Y(_0027_)
  );
  sky130_fd_sc_hd__nand2_2 _0911_ (
    .A(\hac_inst.count[4] ),
    .B(_0341_),
    .Y(_0343_)
  );
  sky130_fd_sc_hd__or2_2 _0912_ (
    .A(\hac_inst.count[4] ),
    .B(_0341_),
    .X(_0344_)
  );
  sky130_fd_sc_hd__and2_2 _0913_ (
    .A(_0343_),
    .B(_0344_),
    .X(_0028_)
  );
  sky130_fd_sc_hd__xnor2_2 _0914_ (
    .A(\hac_inst.count[5] ),
    .B(_0343_),
    .Y(_0029_)
  );
  sky130_fd_sc_hd__and4_2 _0915_ (
    .A(\hac_inst.count[6] ),
    .B(\hac_inst.count[5] ),
    .C(\hac_inst.count[4] ),
    .D(_0341_),
    .X(_0345_)
  );
  sky130_fd_sc_hd__a31o_2 _0916_ (
    .A1(\hac_inst.count[5] ),
    .A2(\hac_inst.count[4] ),
    .A3(_0341_),
    .B1(\hac_inst.count[6] ),
    .X(_0346_)
  );
  sky130_fd_sc_hd__and2b_2 _0917_ (
    .A_N(_0345_),
    .B(_0346_),
    .X(_0030_)
  );
  sky130_fd_sc_hd__xnor2_2 _0918_ (
    .A(_0109_),
    .B(_0345_),
    .Y(_0031_)
  );
  sky130_fd_sc_hd__and3_2 _0919_ (
    .A(\hac_inst.count[8] ),
    .B(\hac_inst.count[7] ),
    .C(_0345_),
    .X(_0347_)
  );
  sky130_fd_sc_hd__a21oi_2 _0920_ (
    .A1(\hac_inst.count[7] ),
    .A2(_0345_),
    .B1(\hac_inst.count[8] ),
    .Y(_0348_)
  );
  sky130_fd_sc_hd__nor2_2 _0921_ (
    .A(_0347_),
    .B(_0348_),
    .Y(_0032_)
  );
  sky130_fd_sc_hd__xor2_2 _0922_ (
    .A(\hac_inst.count[9] ),
    .B(_0347_),
    .X(_0033_)
  );
  sky130_fd_sc_hd__and3_2 _0923_ (
    .A(\hac_inst.count[10] ),
    .B(\hac_inst.count[9] ),
    .C(_0347_),
    .X(_0349_)
  );
  sky130_fd_sc_hd__a21oi_2 _0924_ (
    .A1(\hac_inst.count[9] ),
    .A2(_0347_),
    .B1(\hac_inst.count[10] ),
    .Y(_0350_)
  );
  sky130_fd_sc_hd__nor2_2 _0925_ (
    .A(_0349_),
    .B(_0350_),
    .Y(_0003_)
  );
  sky130_fd_sc_hd__nand2_2 _0926_ (
    .A(\hac_inst.count[11] ),
    .B(_0349_),
    .Y(_0351_)
  );
  sky130_fd_sc_hd__xor2_2 _0927_ (
    .A(\hac_inst.count[11] ),
    .B(_0349_),
    .X(_0004_)
  );
  sky130_fd_sc_hd__xnor2_2 _0928_ (
    .A(\hac_inst.count[12] ),
    .B(_0351_),
    .Y(_0005_)
  );
  sky130_fd_sc_hd__and4_2 _0929_ (
    .A(\hac_inst.count[13] ),
    .B(\hac_inst.count[12] ),
    .C(\hac_inst.count[11] ),
    .D(_0349_),
    .X(_0352_)
  );
  sky130_fd_sc_hd__a31o_2 _0930_ (
    .A1(\hac_inst.count[12] ),
    .A2(\hac_inst.count[11] ),
    .A3(_0349_),
    .B1(\hac_inst.count[13] ),
    .X(_0353_)
  );
  sky130_fd_sc_hd__and2b_2 _0931_ (
    .A_N(_0352_),
    .B(_0353_),
    .X(_0006_)
  );
  sky130_fd_sc_hd__xnor2_2 _0932_ (
    .A(_0107_),
    .B(_0352_),
    .Y(_0007_)
  );
  sky130_fd_sc_hd__a21oi_2 _0933_ (
    .A1(\hac_inst.count[14] ),
    .A2(_0352_),
    .B1(\hac_inst.count[15] ),
    .Y(_0354_)
  );
  sky130_fd_sc_hd__and3_2 _0934_ (
    .A(\hac_inst.count[15] ),
    .B(\hac_inst.count[14] ),
    .C(_0352_),
    .X(_0355_)
  );
  sky130_fd_sc_hd__nor2_2 _0935_ (
    .A(_0354_),
    .B(_0355_),
    .Y(_0008_)
  );
  sky130_fd_sc_hd__and4_2 _0936_ (
    .A(\hac_inst.count[16] ),
    .B(\hac_inst.count[15] ),
    .C(\hac_inst.count[14] ),
    .D(_0352_),
    .X(_0356_)
  );
  sky130_fd_sc_hd__xor2_2 _0937_ (
    .A(\hac_inst.count[16] ),
    .B(_0355_),
    .X(_0009_)
  );
  sky130_fd_sc_hd__nor2_2 _0938_ (
    .A(\hac_inst.count[17] ),
    .B(_0356_),
    .Y(_0357_)
  );
  sky130_fd_sc_hd__and3_2 _0939_ (
    .A(\hac_inst.count[17] ),
    .B(\hac_inst.count[16] ),
    .C(_0355_),
    .X(_0358_)
  );
  sky130_fd_sc_hd__nor2_2 _0940_ (
    .A(_0357_),
    .B(_0358_),
    .Y(_0010_)
  );
  sky130_fd_sc_hd__xor2_2 _0941_ (
    .A(\hac_inst.count[18] ),
    .B(_0358_),
    .X(_0011_)
  );
  sky130_fd_sc_hd__a21oi_2 _0942_ (
    .A1(\hac_inst.count[18] ),
    .A2(_0358_),
    .B1(\hac_inst.count[19] ),
    .Y(_0359_)
  );
  sky130_fd_sc_hd__and4_2 _0943_ (
    .A(\hac_inst.count[19] ),
    .B(\hac_inst.count[18] ),
    .C(\hac_inst.count[17] ),
    .D(_0356_),
    .X(_0360_)
  );
  sky130_fd_sc_hd__and4_2 _0944_ (
    .A(\hac_inst.count[19] ),
    .B(\hac_inst.count[18] ),
    .C(\hac_inst.count[17] ),
    .D(\hac_inst.count[16] ),
    .X(_0361_)
  );
  sky130_fd_sc_hd__nor2_2 _0945_ (
    .A(_0359_),
    .B(_0360_),
    .Y(_0012_)
  );
  sky130_fd_sc_hd__xor2_2 _0946_ (
    .A(\hac_inst.count[20] ),
    .B(_0360_),
    .X(_0014_)
  );
  sky130_fd_sc_hd__a21oi_2 _0947_ (
    .A1(\hac_inst.count[20] ),
    .A2(_0360_),
    .B1(\hac_inst.count[21] ),
    .Y(_0362_)
  );
  sky130_fd_sc_hd__and4_2 _0948_ (
    .A(\hac_inst.count[21] ),
    .B(\hac_inst.count[20] ),
    .C(_0355_),
    .D(_0361_),
    .X(_0363_)
  );
  sky130_fd_sc_hd__nor2_2 _0949_ (
    .A(_0362_),
    .B(_0363_),
    .Y(_0015_)
  );
  sky130_fd_sc_hd__xnor2_2 _0950_ (
    .A(_0105_),
    .B(_0363_),
    .Y(_0016_)
  );
  sky130_fd_sc_hd__a21oi_2 _0951_ (
    .A1(\hac_inst.count[22] ),
    .A2(_0363_),
    .B1(\hac_inst.count[23] ),
    .Y(_0364_)
  );
  sky130_fd_sc_hd__and3_2 _0952_ (
    .A(\hac_inst.count[23] ),
    .B(\hac_inst.count[22] ),
    .C(_0363_),
    .X(_0365_)
  );
  sky130_fd_sc_hd__nor2_2 _0953_ (
    .A(_0364_),
    .B(_0365_),
    .Y(_0017_)
  );
  sky130_fd_sc_hd__xor2_2 _0954_ (
    .A(\hac_inst.count[24] ),
    .B(_0365_),
    .X(_0018_)
  );
  sky130_fd_sc_hd__a21oi_2 _0955_ (
    .A1(\hac_inst.count[24] ),
    .A2(_0365_),
    .B1(\hac_inst.count[25] ),
    .Y(_0366_)
  );
  sky130_fd_sc_hd__and3_2 _0956_ (
    .A(\hac_inst.count[24] ),
    .B(\hac_inst.count[25] ),
    .C(_0365_),
    .X(_0367_)
  );
  sky130_fd_sc_hd__nor2_2 _0957_ (
    .A(_0366_),
    .B(_0367_),
    .Y(_0019_)
  );
  sky130_fd_sc_hd__xnor2_2 _0958_ (
    .A(_0112_),
    .B(_0367_),
    .Y(_0020_)
  );
  sky130_fd_sc_hd__a21oi_2 _0959_ (
    .A1(\hac_inst.count[26] ),
    .A2(_0367_),
    .B1(\hac_inst.count[27] ),
    .Y(_0368_)
  );
  sky130_fd_sc_hd__and3_2 _0960_ (
    .A(\hac_inst.count[26] ),
    .B(\hac_inst.count[27] ),
    .C(_0367_),
    .X(_0369_)
  );
  sky130_fd_sc_hd__nor2_2 _0961_ (
    .A(_0368_),
    .B(_0369_),
    .Y(_0021_)
  );
  sky130_fd_sc_hd__xor2_2 _0962_ (
    .A(\hac_inst.count[28] ),
    .B(_0369_),
    .X(_0022_)
  );
  sky130_fd_sc_hd__a21oi_2 _0963_ (
    .A1(\hac_inst.count[28] ),
    .A2(_0369_),
    .B1(\hac_inst.count[29] ),
    .Y(_0370_)
  );
  sky130_fd_sc_hd__and3_2 _0964_ (
    .A(\hac_inst.count[28] ),
    .B(\hac_inst.count[29] ),
    .C(_0369_),
    .X(_0371_)
  );
  sky130_fd_sc_hd__nor2_2 _0965_ (
    .A(_0370_),
    .B(_0371_),
    .Y(_0023_)
  );
  sky130_fd_sc_hd__or2_2 _0966_ (
    .A(\hac_inst.count[30] ),
    .B(_0371_),
    .X(_0372_)
  );
  sky130_fd_sc_hd__nand2_2 _0967_ (
    .A(\hac_inst.count[30] ),
    .B(_0371_),
    .Y(_0373_)
  );
  sky130_fd_sc_hd__and2_2 _0968_ (
    .A(_0372_),
    .B(_0373_),
    .X(_0025_)
  );
  sky130_fd_sc_hd__xnor2_2 _0969_ (
    .A(\hac_inst.count[31] ),
    .B(_0373_),
    .Y(_0026_)
  );
  sky130_fd_sc_hd__xor2_2 _0970_ (
    .A(_0123_),
    .B(_0186_),
    .X(hac_val[1])
  );
  sky130_fd_sc_hd__xnor2_2 _0971_ (
    .A(_0184_),
    .B(_0187_),
    .Y(hac_val[2])
  );
  sky130_fd_sc_hd__xnor2_2 _0972_ (
    .A(_0188_),
    .B(_0190_),
    .Y(hac_val[3])
  );
  sky130_fd_sc_hd__or2_2 _0973_ (
    .A(_0191_),
    .B(_0192_),
    .X(_0374_)
  );
  sky130_fd_sc_hd__and2_2 _0974_ (
    .A(_0193_),
    .B(_0374_),
    .X(hac_val[4])
  );
  sky130_fd_sc_hd__a21bo_2 _0975_ (
    .A1(_0110_),
    .A2(\hac_inst.count[4] ),
    .B1_N(_0193_),
    .X(_0375_)
  );
  sky130_fd_sc_hd__xor2_2 _0976_ (
    .A(_0196_),
    .B(_0375_),
    .X(hac_val[5])
  );
  sky130_fd_sc_hd__xor2_2 _0977_ (
    .A(_0176_),
    .B(_0194_),
    .X(hac_val[6])
  );
  sky130_fd_sc_hd__o21ai_2 _0978_ (
    .A1(_0176_),
    .A2(_0194_),
    .B1(_0174_),
    .Y(_0376_)
  );
  sky130_fd_sc_hd__xnor2_2 _0979_ (
    .A(_0177_),
    .B(_0376_),
    .Y(hac_val[7])
  );
  sky130_fd_sc_hd__xnor2_2 _0980_ (
    .A(_0201_),
    .B(_0203_),
    .Y(hac_val[8])
  );
  sky130_fd_sc_hd__nand2_2 _0981_ (
    .A(_0202_),
    .B(_0204_),
    .Y(_0377_)
  );
  sky130_fd_sc_hd__xor2_2 _0982_ (
    .A(_0207_),
    .B(_0377_),
    .X(hac_val[9])
  );
  sky130_fd_sc_hd__xnor2_2 _0983_ (
    .A(_0171_),
    .B(_0208_),
    .Y(hac_val[10])
  );
  sky130_fd_sc_hd__o21a_2 _0984_ (
    .A1(_0172_),
    .A2(_0208_),
    .B1(_0167_),
    .X(_0378_)
  );
  sky130_fd_sc_hd__xnor2_2 _0985_ (
    .A(_0169_),
    .B(_0378_),
    .Y(hac_val[11])
  );
  sky130_fd_sc_hd__a21oi_2 _0986_ (
    .A1(_0209_),
    .A2(_0211_),
    .B1(_0163_),
    .Y(_0379_)
  );
  sky130_fd_sc_hd__and3_2 _0987_ (
    .A(_0163_),
    .B(_0209_),
    .C(_0211_),
    .X(_0380_)
  );
  sky130_fd_sc_hd__nor2_2 _0988_ (
    .A(_0379_),
    .B(_0380_),
    .Y(hac_val[12])
  );
  sky130_fd_sc_hd__nor2_2 _0989_ (
    .A(_0161_),
    .B(_0379_),
    .Y(_0381_)
  );
  sky130_fd_sc_hd__xnor2_2 _0990_ (
    .A(_0160_),
    .B(_0381_),
    .Y(hac_val[13])
  );
  sky130_fd_sc_hd__o21a_2 _0991_ (
    .A1(_0214_),
    .A2(_0379_),
    .B1(_0159_),
    .X(_0382_)
  );
  sky130_fd_sc_hd__xor2_2 _0992_ (
    .A(_0156_),
    .B(_0382_),
    .X(hac_val[14])
  );
  sky130_fd_sc_hd__a21oi_2 _0993_ (
    .A1(_0156_),
    .A2(_0382_),
    .B1(_0154_),
    .Y(_0383_)
  );
  sky130_fd_sc_hd__xnor2_2 _0994_ (
    .A(_0153_),
    .B(_0383_),
    .Y(hac_val[15])
  );
  sky130_fd_sc_hd__xnor2_2 _0995_ (
    .A(_0152_),
    .B(_0217_),
    .Y(hac_val[16])
  );
  sky130_fd_sc_hd__nand2_2 _0996_ (
    .A(_0150_),
    .B(_0218_),
    .Y(_0384_)
  );
  sky130_fd_sc_hd__xor2_2 _0997_ (
    .A(_0149_),
    .B(_0384_),
    .X(hac_val[17])
  );
  sky130_fd_sc_hd__xnor2_2 _0998_ (
    .A(_0144_),
    .B(_0219_),
    .Y(hac_val[18])
  );
  sky130_fd_sc_hd__o211a_2 _0999_ (
    .A1(_0140_),
    .A2(_0142_),
    .B1(_0143_),
    .C1(_0220_),
    .X(_0385_)
  );
  sky130_fd_sc_hd__a211oi_2 _1000_ (
    .A1(_0143_),
    .A2(_0220_),
    .B1(_0140_),
    .C1(_0142_),
    .Y(_0386_)
  );
  sky130_fd_sc_hd__nor2_2 _1001_ (
    .A(_0385_),
    .B(_0386_),
    .Y(hac_val[19])
  );
  sky130_fd_sc_hd__and2_2 _1002_ (
    .A(_0139_),
    .B(_0221_),
    .X(_0387_)
  );
  sky130_fd_sc_hd__nor2_2 _1003_ (
    .A(_0222_),
    .B(_0387_),
    .Y(hac_val[20])
  );
  sky130_fd_sc_hd__nor2_2 _1004_ (
    .A(_0134_),
    .B(_0222_),
    .Y(_0388_)
  );
  sky130_fd_sc_hd__xnor2_2 _1005_ (
    .A(_0136_),
    .B(_0388_),
    .Y(hac_val[21])
  );
  sky130_fd_sc_hd__a211oi_2 _1006_ (
    .A1(_0136_),
    .A2(_0222_),
    .B1(_0130_),
    .C1(_0135_),
    .Y(_0389_)
  );
  sky130_fd_sc_hd__nor2_2 _1007_ (
    .A(_0223_),
    .B(_0389_),
    .Y(hac_val[22])
  );
  sky130_fd_sc_hd__or3b_2 _1008_ (
    .A(instr_data[19]),
    .B(instr_data[18]),
    .C_N(instr_data[16]),
    .X(_0390_)
  );
  sky130_fd_sc_hd__or4_2 _1009_ (
    .A(instr_data[21]),
    .B(instr_data[20]),
    .C(instr_data[23]),
    .D(instr_data[22]),
    .X(_0391_)
  );
  sky130_fd_sc_hd__or3_2 _1010_ (
    .A(_0103_),
    .B(_0390_),
    .C(_0391_),
    .X(_0392_)
  );
  sky130_fd_sc_hd__xnor2_2 _1011_ (
    .A(_0101_),
    .B(_0392_),
    .Y(_0034_)
  );
  sky130_fd_sc_hd__o311a_2 _1012_ (
    .A1(_0103_),
    .A2(_0390_),
    .A3(_0391_),
    .B1(sac_val[1]),
    .C1(sac_val[0]),
    .X(_0393_)
  );
  sky130_fd_sc_hd__a21oi_2 _1013_ (
    .A1(sac_val[0]),
    .A2(_0392_),
    .B1(sac_val[1]),
    .Y(_0394_)
  );
  sky130_fd_sc_hd__nor2_2 _1014_ (
    .A(_0393_),
    .B(_0394_),
    .Y(_0035_)
  );
  sky130_fd_sc_hd__nand2_2 _1015_ (
    .A(sac_val[2]),
    .B(_0393_),
    .Y(_0395_)
  );
  sky130_fd_sc_hd__xor2_2 _1016_ (
    .A(sac_val[2]),
    .B(_0393_),
    .X(_0036_)
  );
  sky130_fd_sc_hd__xnor2_2 _1017_ (
    .A(sac_val[3]),
    .B(_0395_),
    .Y(_0037_)
  );
  sky130_fd_sc_hd__and4_2 _1018_ (
    .A(sac_val[2]),
    .B(sac_val[3]),
    .C(sac_val[4]),
    .D(_0393_),
    .X(_0396_)
  );
  sky130_fd_sc_hd__a31o_2 _1019_ (
    .A1(sac_val[2]),
    .A2(sac_val[3]),
    .A3(_0393_),
    .B1(sac_val[4]),
    .X(_0397_)
  );
  sky130_fd_sc_hd__and2b_2 _1020_ (
    .A_N(_0396_),
    .B(_0397_),
    .X(_0038_)
  );
  sky130_fd_sc_hd__nand2_2 _1021_ (
    .A(sac_val[5]),
    .B(_0396_),
    .Y(_0398_)
  );
  sky130_fd_sc_hd__or2_2 _1022_ (
    .A(sac_val[5]),
    .B(_0396_),
    .X(_0399_)
  );
  sky130_fd_sc_hd__and2_2 _1023_ (
    .A(_0398_),
    .B(_0399_),
    .X(_0039_)
  );
  sky130_fd_sc_hd__xnor2_2 _1024_ (
    .A(sac_val[6]),
    .B(_0398_),
    .Y(_0040_)
  );
  sky130_fd_sc_hd__and4_2 _1025_ (
    .A(sac_val[5]),
    .B(sac_val[6]),
    .C(sac_val[7]),
    .D(_0396_),
    .X(_0400_)
  );
  sky130_fd_sc_hd__a31o_2 _1026_ (
    .A1(sac_val[5]),
    .A2(sac_val[6]),
    .A3(_0396_),
    .B1(sac_val[7]),
    .X(_0401_)
  );
  sky130_fd_sc_hd__and2b_2 _1027_ (
    .A_N(_0400_),
    .B(_0401_),
    .X(_0041_)
  );
  sky130_fd_sc_hd__nand2_2 _1028_ (
    .A(sac_val[8]),
    .B(_0400_),
    .Y(_0402_)
  );
  sky130_fd_sc_hd__or2_2 _1029_ (
    .A(sac_val[8]),
    .B(_0400_),
    .X(_0403_)
  );
  sky130_fd_sc_hd__and2_2 _1030_ (
    .A(_0402_),
    .B(_0403_),
    .X(_0042_)
  );
  sky130_fd_sc_hd__xnor2_2 _1031_ (
    .A(sac_val[9]),
    .B(_0402_),
    .Y(_0043_)
  );
  sky130_fd_sc_hd__and4_2 _1032_ (
    .A(sac_val[8]),
    .B(sac_val[9]),
    .C(sac_val[10]),
    .D(_0400_),
    .X(_0404_)
  );
  sky130_fd_sc_hd__a31o_2 _1033_ (
    .A1(sac_val[8]),
    .A2(sac_val[9]),
    .A3(_0400_),
    .B1(sac_val[10]),
    .X(_0405_)
  );
  sky130_fd_sc_hd__and2b_2 _1034_ (
    .A_N(_0404_),
    .B(_0405_),
    .X(_0044_)
  );
  sky130_fd_sc_hd__nand2_2 _1035_ (
    .A(sac_val[11]),
    .B(_0404_),
    .Y(_0406_)
  );
  sky130_fd_sc_hd__xor2_2 _1036_ (
    .A(sac_val[11]),
    .B(_0404_),
    .X(_0045_)
  );
  sky130_fd_sc_hd__xnor2_2 _1037_ (
    .A(sac_val[12]),
    .B(_0406_),
    .Y(_0046_)
  );
  sky130_fd_sc_hd__and4_2 _1038_ (
    .A(sac_val[11]),
    .B(sac_val[12]),
    .C(sac_val[13]),
    .D(_0404_),
    .X(_0407_)
  );
  sky130_fd_sc_hd__a31o_2 _1039_ (
    .A1(sac_val[11]),
    .A2(sac_val[12]),
    .A3(_0404_),
    .B1(sac_val[13]),
    .X(_0408_)
  );
  sky130_fd_sc_hd__and2b_2 _1040_ (
    .A_N(_0407_),
    .B(_0408_),
    .X(_0047_)
  );
  sky130_fd_sc_hd__nand2_2 _1041_ (
    .A(sac_val[14]),
    .B(_0407_),
    .Y(_0409_)
  );
  sky130_fd_sc_hd__or2_2 _1042_ (
    .A(sac_val[14]),
    .B(_0407_),
    .X(_0410_)
  );
  sky130_fd_sc_hd__and2_2 _1043_ (
    .A(_0409_),
    .B(_0410_),
    .X(_0048_)
  );
  sky130_fd_sc_hd__xnor2_2 _1044_ (
    .A(sac_val[15]),
    .B(_0409_),
    .Y(_0049_)
  );
  sky130_fd_sc_hd__and4_2 _1045_ (
    .A(sac_val[14]),
    .B(sac_val[15]),
    .C(sac_val[16]),
    .D(_0407_),
    .X(_0411_)
  );
  sky130_fd_sc_hd__a31o_2 _1046_ (
    .A1(sac_val[14]),
    .A2(sac_val[15]),
    .A3(_0407_),
    .B1(sac_val[16]),
    .X(_0412_)
  );
  sky130_fd_sc_hd__and2b_2 _1047_ (
    .A_N(_0411_),
    .B(_0412_),
    .X(_0050_)
  );
  sky130_fd_sc_hd__nand2_2 _1048_ (
    .A(sac_val[17]),
    .B(_0411_),
    .Y(_0413_)
  );
  sky130_fd_sc_hd__or2_2 _1049_ (
    .A(sac_val[17]),
    .B(_0411_),
    .X(_0414_)
  );
  sky130_fd_sc_hd__and2_2 _1050_ (
    .A(_0413_),
    .B(_0414_),
    .X(_0051_)
  );
  sky130_fd_sc_hd__xnor2_2 _1051_ (
    .A(sac_val[18]),
    .B(_0413_),
    .Y(_0052_)
  );
  sky130_fd_sc_hd__and4_2 _1052_ (
    .A(sac_val[17]),
    .B(sac_val[18]),
    .C(sac_val[19]),
    .D(_0411_),
    .X(_0415_)
  );
  sky130_fd_sc_hd__a31o_2 _1053_ (
    .A1(sac_val[17]),
    .A2(sac_val[18]),
    .A3(_0411_),
    .B1(sac_val[19]),
    .X(_0416_)
  );
  sky130_fd_sc_hd__and2b_2 _1054_ (
    .A_N(_0415_),
    .B(_0416_),
    .X(_0053_)
  );
  sky130_fd_sc_hd__nand2_2 _1055_ (
    .A(sac_val[20]),
    .B(_0415_),
    .Y(_0417_)
  );
  sky130_fd_sc_hd__or2_2 _1056_ (
    .A(sac_val[20]),
    .B(_0415_),
    .X(_0418_)
  );
  sky130_fd_sc_hd__and2_2 _1057_ (
    .A(_0417_),
    .B(_0418_),
    .X(_0054_)
  );
  sky130_fd_sc_hd__xnor2_2 _1058_ (
    .A(sac_val[21]),
    .B(_0417_),
    .Y(_0055_)
  );
  sky130_fd_sc_hd__and4_2 _1059_ (
    .A(sac_val[20]),
    .B(sac_val[21]),
    .C(sac_val[22]),
    .D(_0415_),
    .X(_0419_)
  );
  sky130_fd_sc_hd__a31o_2 _1060_ (
    .A1(sac_val[20]),
    .A2(sac_val[21]),
    .A3(_0415_),
    .B1(sac_val[22]),
    .X(_0420_)
  );
  sky130_fd_sc_hd__and2b_2 _1061_ (
    .A_N(_0419_),
    .B(_0420_),
    .X(_0056_)
  );
  sky130_fd_sc_hd__nand2_2 _1062_ (
    .A(sac_val[23]),
    .B(_0419_),
    .Y(_0421_)
  );
  sky130_fd_sc_hd__or2_2 _1063_ (
    .A(sac_val[23]),
    .B(_0419_),
    .X(_0422_)
  );
  sky130_fd_sc_hd__and2_2 _1064_ (
    .A(_0421_),
    .B(_0422_),
    .X(_0057_)
  );
  sky130_fd_sc_hd__xnor2_2 _1065_ (
    .A(sac_val[24]),
    .B(_0421_),
    .Y(_0058_)
  );
  sky130_fd_sc_hd__and4_2 _1066_ (
    .A(sac_val[23]),
    .B(sac_val[24]),
    .C(sac_val[25]),
    .D(_0419_),
    .X(_0423_)
  );
  sky130_fd_sc_hd__a31o_2 _1067_ (
    .A1(sac_val[23]),
    .A2(sac_val[24]),
    .A3(_0419_),
    .B1(sac_val[25]),
    .X(_0424_)
  );
  sky130_fd_sc_hd__and2b_2 _1068_ (
    .A_N(_0423_),
    .B(_0424_),
    .X(_0059_)
  );
  sky130_fd_sc_hd__nand2_2 _1069_ (
    .A(sac_val[26]),
    .B(_0423_),
    .Y(_0425_)
  );
  sky130_fd_sc_hd__or2_2 _1070_ (
    .A(sac_val[26]),
    .B(_0423_),
    .X(_0426_)
  );
  sky130_fd_sc_hd__and2_2 _1071_ (
    .A(_0425_),
    .B(_0426_),
    .X(_0060_)
  );
  sky130_fd_sc_hd__xnor2_2 _1072_ (
    .A(sac_val[27]),
    .B(_0425_),
    .Y(_0061_)
  );
  sky130_fd_sc_hd__and4_2 _1073_ (
    .A(sac_val[26]),
    .B(sac_val[27]),
    .C(sac_val[28]),
    .D(_0423_),
    .X(_0427_)
  );
  sky130_fd_sc_hd__a31o_2 _1074_ (
    .A1(sac_val[26]),
    .A2(sac_val[27]),
    .A3(_0423_),
    .B1(sac_val[28]),
    .X(_0428_)
  );
  sky130_fd_sc_hd__and2b_2 _1075_ (
    .A_N(_0427_),
    .B(_0428_),
    .X(_0062_)
  );
  sky130_fd_sc_hd__xor2_2 _1076_ (
    .A(sac_val[29]),
    .B(_0427_),
    .X(_0063_)
  );
  sky130_fd_sc_hd__and3_2 _1077_ (
    .A(sac_val[29]),
    .B(sac_val[30]),
    .C(_0427_),
    .X(_0429_)
  );
  sky130_fd_sc_hd__a21oi_2 _1078_ (
    .A1(sac_val[29]),
    .A2(_0427_),
    .B1(sac_val[30]),
    .Y(_0430_)
  );
  sky130_fd_sc_hd__nor2_2 _1079_ (
    .A(_0429_),
    .B(_0430_),
    .Y(_0064_)
  );
  sky130_fd_sc_hd__xor2_2 _1080_ (
    .A(sac_val[31]),
    .B(_0429_),
    .X(_0065_)
  );
  sky130_fd_sc_hd__nand3b_2 _1081_ (
    .A_N(link_rx[46]),
    .B(link_rx[47]),
    .C(link_rx_v),
    .Y(_0431_)
  );
  sky130_fd_sc_hd__or4b_2 _1082_ (
    .A(link_rx[43]),
    .B(link_rx[42]),
    .C(link_rx[44]),
    .D_N(link_rx[45]),
    .X(_0432_)
  );
  sky130_fd_sc_hd__or4_2 _1083_ (
    .A(link_rx[41]),
    .B(link_rx[40]),
    .C(_0431_),
    .D(_0432_),
    .X(_0433_)
  );
  sky130_fd_sc_hd__nor2_2 _1084_ (
    .A(phase_status[0]),
    .B(_0433_),
    .Y(_0066_)
  );
  sky130_fd_sc_hd__a21o_2 _1085_ (
    .A1(phase_status[4]),
    .A2(link_tx_r),
    .B1(phase_status[5]),
    .X(_0434_)
  );
  sky130_fd_sc_hd__o21ai_2 _1086_ (
    .A1(phase_status[4]),
    .A2(_0433_),
    .B1(_0434_),
    .Y(_0435_)
  );
  sky130_fd_sc_hd__or4_2 _1087_ (
    .A(instr_data[25]),
    .B(instr_data[24]),
    .C(instr_data[27]),
    .D(instr_data[26]),
    .X(_0436_)
  );
  sky130_fd_sc_hd__or3b_2 _1088_ (
    .A(_0436_),
    .B(instr_data[17]),
    .C_N(instr_valid),
    .X(_0437_)
  );
  sky130_fd_sc_hd__or4b_2 _1089_ (
    .A(instr_data[29]),
    .B(instr_data[31]),
    .C(instr_data[30]),
    .D_N(instr_data[28]),
    .X(_0438_)
  );
  sky130_fd_sc_hd__nor4_2 _1090_ (
    .A(_0390_),
    .B(_0391_),
    .C(_0437_),
    .D(_0438_),
    .Y(_0439_)
  );
  sky130_fd_sc_hd__o31a_2 _1091_ (
    .A1(phase_status[5]),
    .A2(phase_status[4]),
    .A3(_0439_),
    .B1(_0435_),
    .X(_0067_)
  );
  sky130_fd_sc_hd__a21boi_2 _1092_ (
    .A1(phase_status[5]),
    .A2(phase_status[4]),
    .B1_N(_0434_),
    .Y(_0068_)
  );
  sky130_fd_sc_hd__nor2_2 _1093_ (
    .A(_0002_),
    .B(link_rx[8]),
    .Y(_0440_)
  );
  sky130_fd_sc_hd__nand2b_2 _1094_ (
    .A_N(\hac_inst.count[0] ),
    .B(link_rx[8]),
    .Y(_0441_)
  );
  sky130_fd_sc_hd__nand2_2 _1095_ (
    .A(phase_status[0]),
    .B(_0441_),
    .Y(_0442_)
  );
  sky130_fd_sc_hd__o22a_2 _1096_ (
    .A1(\hac_offset[0] ),
    .A2(phase_status[0]),
    .B1(_0440_),
    .B2(_0442_),
    .X(_0069_)
  );
  sky130_fd_sc_hd__and2b_2 _1097_ (
    .A_N(link_rx[9]),
    .B(\hac_inst.count[1] ),
    .X(_0443_)
  );
  sky130_fd_sc_hd__nand2b_2 _1098_ (
    .A_N(\hac_inst.count[1] ),
    .B(link_rx[9]),
    .Y(_0444_)
  );
  sky130_fd_sc_hd__nand2b_2 _1099_ (
    .A_N(_0443_),
    .B(_0444_),
    .Y(_0445_)
  );
  sky130_fd_sc_hd__xnor2_2 _1100_ (
    .A(_0441_),
    .B(_0445_),
    .Y(_0446_)
  );
  sky130_fd_sc_hd__mux2_1 _1101_ (
    .A0(\hac_offset[1] ),
    .A1(_0446_),
    .S(phase_status[0]),
    .X(_0070_)
  );
  sky130_fd_sc_hd__a21o_2 _1102_ (
    .A1(_0441_),
    .A2(_0444_),
    .B1(_0443_),
    .X(_0447_)
  );
  sky130_fd_sc_hd__and2b_2 _1103_ (
    .A_N(\hac_inst.count[2] ),
    .B(link_rx[10]),
    .X(_0448_)
  );
  sky130_fd_sc_hd__and2b_2 _1104_ (
    .A_N(link_rx[10]),
    .B(\hac_inst.count[2] ),
    .X(_0449_)
  );
  sky130_fd_sc_hd__nor2_2 _1105_ (
    .A(_0448_),
    .B(_0449_),
    .Y(_0450_)
  );
  sky130_fd_sc_hd__nand2_2 _1106_ (
    .A(_0447_),
    .B(_0450_),
    .Y(_0451_)
  );
  sky130_fd_sc_hd__o21a_2 _1107_ (
    .A1(_0447_),
    .A2(_0450_),
    .B1(phase_status[0]),
    .X(_0452_)
  );
  sky130_fd_sc_hd__a22o_2 _1108_ (
    .A1(_0102_),
    .A2(\hac_offset[2] ),
    .B1(_0451_),
    .B2(_0452_),
    .X(_0071_)
  );
  sky130_fd_sc_hd__and2b_2 _1109_ (
    .A_N(\hac_inst.count[3] ),
    .B(link_rx[11]),
    .X(_0453_)
  );
  sky130_fd_sc_hd__and2b_2 _1110_ (
    .A_N(link_rx[11]),
    .B(\hac_inst.count[3] ),
    .X(_0454_)
  );
  sky130_fd_sc_hd__nor2_2 _1111_ (
    .A(_0453_),
    .B(_0454_),
    .Y(_0455_)
  );
  sky130_fd_sc_hd__a21oi_2 _1112_ (
    .A1(_0447_),
    .A2(_0450_),
    .B1(_0449_),
    .Y(_0456_)
  );
  sky130_fd_sc_hd__xnor2_2 _1113_ (
    .A(_0455_),
    .B(_0456_),
    .Y(_0457_)
  );
  sky130_fd_sc_hd__mux2_1 _1114_ (
    .A0(\hac_offset[3] ),
    .A1(_0457_),
    .S(phase_status[0]),
    .X(_0072_)
  );
  sky130_fd_sc_hd__nand2b_2 _1115_ (
    .A_N(\hac_inst.count[4] ),
    .B(link_rx[12]),
    .Y(_0458_)
  );
  sky130_fd_sc_hd__nand2b_2 _1116_ (
    .A_N(link_rx[12]),
    .B(\hac_inst.count[4] ),
    .Y(_0459_)
  );
  sky130_fd_sc_hd__nand2_2 _1117_ (
    .A(_0458_),
    .B(_0459_),
    .Y(_0460_)
  );
  sky130_fd_sc_hd__nor3b_2 _1118_ (
    .A(link_rx[10]),
    .B(_0453_),
    .C_N(\hac_inst.count[2] ),
    .Y(_0461_)
  );
  sky130_fd_sc_hd__a311o_2 _1119_ (
    .A1(_0447_),
    .A2(_0450_),
    .A3(_0455_),
    .B1(_0461_),
    .C1(_0454_),
    .X(_0462_)
  );
  sky130_fd_sc_hd__xnor2_2 _1120_ (
    .A(_0460_),
    .B(_0462_),
    .Y(_0463_)
  );
  sky130_fd_sc_hd__mux2_1 _1121_ (
    .A0(\hac_offset[4] ),
    .A1(_0463_),
    .S(phase_status[0]),
    .X(_0073_)
  );
  sky130_fd_sc_hd__nand2b_2 _1122_ (
    .A_N(\hac_inst.count[5] ),
    .B(link_rx[13]),
    .Y(_0464_)
  );
  sky130_fd_sc_hd__and2b_2 _1123_ (
    .A_N(link_rx[13]),
    .B(\hac_inst.count[5] ),
    .X(_0465_)
  );
  sky130_fd_sc_hd__nand2b_2 _1124_ (
    .A_N(link_rx[13]),
    .B(\hac_inst.count[5] ),
    .Y(_0466_)
  );
  sky130_fd_sc_hd__nand2_2 _1125_ (
    .A(_0464_),
    .B(_0466_),
    .Y(_0467_)
  );
  sky130_fd_sc_hd__a21bo_2 _1126_ (
    .A1(_0458_),
    .A2(_0462_),
    .B1_N(_0459_),
    .X(_0468_)
  );
  sky130_fd_sc_hd__xnor2_2 _1127_ (
    .A(_0467_),
    .B(_0468_),
    .Y(_0469_)
  );
  sky130_fd_sc_hd__mux2_1 _1128_ (
    .A0(\hac_offset[5] ),
    .A1(_0469_),
    .S(phase_status[0]),
    .X(_0074_)
  );
  sky130_fd_sc_hd__xnor2_2 _1129_ (
    .A(\hac_inst.count[6] ),
    .B(link_rx[14]),
    .Y(_0470_)
  );
  sky130_fd_sc_hd__a31o_2 _1130_ (
    .A1(\hac_inst.count[4] ),
    .A2(_0117_),
    .A3(_0464_),
    .B1(_0465_),
    .X(_0471_)
  );
  sky130_fd_sc_hd__nor2_2 _1131_ (
    .A(_0460_),
    .B(_0467_),
    .Y(_0472_)
  );
  sky130_fd_sc_hd__a21o_2 _1132_ (
    .A1(_0462_),
    .A2(_0472_),
    .B1(_0471_),
    .X(_0473_)
  );
  sky130_fd_sc_hd__nand2_2 _1133_ (
    .A(_0470_),
    .B(_0473_),
    .Y(_0474_)
  );
  sky130_fd_sc_hd__or2_2 _1134_ (
    .A(_0470_),
    .B(_0473_),
    .X(_0475_)
  );
  sky130_fd_sc_hd__and3_2 _1135_ (
    .A(phase_status[0]),
    .B(_0474_),
    .C(_0475_),
    .X(_0476_)
  );
  sky130_fd_sc_hd__a21o_2 _1136_ (
    .A1(_0102_),
    .A2(\hac_offset[6] ),
    .B1(_0476_),
    .X(_0075_)
  );
  sky130_fd_sc_hd__and2b_2 _1137_ (
    .A_N(\hac_inst.count[7] ),
    .B(link_rx[15]),
    .X(_0477_)
  );
  sky130_fd_sc_hd__nand2b_2 _1138_ (
    .A_N(\hac_inst.count[7] ),
    .B(link_rx[15]),
    .Y(_0478_)
  );
  sky130_fd_sc_hd__and2b_2 _1139_ (
    .A_N(link_rx[15]),
    .B(\hac_inst.count[7] ),
    .X(_0479_)
  );
  sky130_fd_sc_hd__nor2_2 _1140_ (
    .A(_0477_),
    .B(_0479_),
    .Y(_0480_)
  );
  sky130_fd_sc_hd__a21bo_2 _1141_ (
    .A1(\hac_inst.count[6] ),
    .A2(_0118_),
    .B1_N(_0474_),
    .X(_0481_)
  );
  sky130_fd_sc_hd__xor2_2 _1142_ (
    .A(_0480_),
    .B(_0481_),
    .X(_0482_)
  );
  sky130_fd_sc_hd__mux2_1 _1143_ (
    .A0(\hac_offset[7] ),
    .A1(_0482_),
    .S(phase_status[0]),
    .X(_0076_)
  );
  sky130_fd_sc_hd__and2_2 _1144_ (
    .A(_0108_),
    .B(link_rx[16]),
    .X(_0483_)
  );
  sky130_fd_sc_hd__nor2_2 _1145_ (
    .A(_0108_),
    .B(link_rx[16]),
    .Y(_0484_)
  );
  sky130_fd_sc_hd__nor2_2 _1146_ (
    .A(_0483_),
    .B(_0484_),
    .Y(_0485_)
  );
  sky130_fd_sc_hd__a31o_2 _1147_ (
    .A1(\hac_inst.count[6] ),
    .A2(_0118_),
    .A3(_0478_),
    .B1(_0479_),
    .X(_0486_)
  );
  sky130_fd_sc_hd__a31o_2 _1148_ (
    .A1(_0470_),
    .A2(_0471_),
    .A3(_0480_),
    .B1(_0486_),
    .X(_0487_)
  );
  sky130_fd_sc_hd__and2_2 _1149_ (
    .A(_0470_),
    .B(_0480_),
    .X(_0488_)
  );
  sky130_fd_sc_hd__a31o_2 _1150_ (
    .A1(_0462_),
    .A2(_0472_),
    .A3(_0488_),
    .B1(_0487_),
    .X(_0489_)
  );
  sky130_fd_sc_hd__xor2_2 _1151_ (
    .A(_0485_),
    .B(_0489_),
    .X(_0490_)
  );
  sky130_fd_sc_hd__mux2_1 _1152_ (
    .A0(\hac_offset[8] ),
    .A1(_0490_),
    .S(phase_status[0]),
    .X(_0077_)
  );
  sky130_fd_sc_hd__nand2b_2 _1153_ (
    .A_N(\hac_inst.count[9] ),
    .B(link_rx[17]),
    .Y(_0491_)
  );
  sky130_fd_sc_hd__a21oi_2 _1154_ (
    .A1(_0485_),
    .A2(_0489_),
    .B1(_0484_),
    .Y(_0492_)
  );
  sky130_fd_sc_hd__and2b_2 _1155_ (
    .A_N(link_rx[17]),
    .B(\hac_inst.count[9] ),
    .X(_0493_)
  );
  sky130_fd_sc_hd__nand2b_2 _1156_ (
    .A_N(link_rx[17]),
    .B(\hac_inst.count[9] ),
    .Y(_0494_)
  );
  sky130_fd_sc_hd__nand2_2 _1157_ (
    .A(_0492_),
    .B(_0494_),
    .Y(_0495_)
  );
  sky130_fd_sc_hd__and2_2 _1158_ (
    .A(_0491_),
    .B(_0494_),
    .X(_0496_)
  );
  sky130_fd_sc_hd__xnor2_2 _1159_ (
    .A(_0492_),
    .B(_0496_),
    .Y(_0497_)
  );
  sky130_fd_sc_hd__mux2_1 _1160_ (
    .A0(\hac_offset[9] ),
    .A1(_0497_),
    .S(phase_status[0]),
    .X(_0078_)
  );
  sky130_fd_sc_hd__and2b_2 _1161_ (
    .A_N(\hac_inst.count[10] ),
    .B(link_rx[18]),
    .X(_0498_)
  );
  sky130_fd_sc_hd__and2b_2 _1162_ (
    .A_N(link_rx[18]),
    .B(\hac_inst.count[10] ),
    .X(_0499_)
  );
  sky130_fd_sc_hd__nor2_2 _1163_ (
    .A(_0498_),
    .B(_0499_),
    .Y(_0500_)
  );
  sky130_fd_sc_hd__and3_2 _1164_ (
    .A(_0491_),
    .B(_0495_),
    .C(_0500_),
    .X(_0501_)
  );
  sky130_fd_sc_hd__a21oi_2 _1165_ (
    .A1(_0491_),
    .A2(_0495_),
    .B1(_0500_),
    .Y(_0502_)
  );
  sky130_fd_sc_hd__nor2_2 _1166_ (
    .A(_0501_),
    .B(_0502_),
    .Y(_0503_)
  );
  sky130_fd_sc_hd__mux2_1 _1167_ (
    .A0(\hac_offset[10] ),
    .A1(_0503_),
    .S(phase_status[0]),
    .X(_0079_)
  );
  sky130_fd_sc_hd__and2b_2 _1168_ (
    .A_N(\hac_inst.count[11] ),
    .B(link_rx[19]),
    .X(_0504_)
  );
  sky130_fd_sc_hd__and2b_2 _1169_ (
    .A_N(link_rx[19]),
    .B(\hac_inst.count[11] ),
    .X(_0505_)
  );
  sky130_fd_sc_hd__nor2_2 _1170_ (
    .A(_0504_),
    .B(_0505_),
    .Y(_0506_)
  );
  sky130_fd_sc_hd__o21ai_2 _1171_ (
    .A1(_0499_),
    .A2(_0501_),
    .B1(_0506_),
    .Y(_0507_)
  );
  sky130_fd_sc_hd__o31a_2 _1172_ (
    .A1(_0499_),
    .A2(_0501_),
    .A3(_0506_),
    .B1(phase_status[0]),
    .X(_0508_)
  );
  sky130_fd_sc_hd__a22o_2 _1173_ (
    .A1(_0102_),
    .A2(\hac_offset[11] ),
    .B1(_0507_),
    .B2(_0508_),
    .X(_0080_)
  );
  sky130_fd_sc_hd__and2b_2 _1174_ (
    .A_N(\hac_inst.count[12] ),
    .B(link_rx[20]),
    .X(_0509_)
  );
  sky130_fd_sc_hd__and2b_2 _1175_ (
    .A_N(link_rx[20]),
    .B(\hac_inst.count[12] ),
    .X(_0510_)
  );
  sky130_fd_sc_hd__or2_2 _1176_ (
    .A(_0509_),
    .B(_0510_),
    .X(_0511_)
  );
  sky130_fd_sc_hd__and4_2 _1177_ (
    .A(_0485_),
    .B(_0496_),
    .C(_0500_),
    .D(_0506_),
    .X(_0512_)
  );
  sky130_fd_sc_hd__o2111a_2 _1178_ (
    .A1(_0484_),
    .A2(_0493_),
    .B1(_0500_),
    .C1(_0506_),
    .D1(_0491_),
    .X(_0513_)
  );
  sky130_fd_sc_hd__nor2_2 _1179_ (
    .A(link_rx[18]),
    .B(_0504_),
    .Y(_0514_)
  );
  sky130_fd_sc_hd__a211oi_2 _1180_ (
    .A1(\hac_inst.count[10] ),
    .A2(_0514_),
    .B1(_0513_),
    .C1(_0505_),
    .Y(_0515_)
  );
  sky130_fd_sc_hd__a21boi_2 _1181_ (
    .A1(_0489_),
    .A2(_0512_),
    .B1_N(_0515_),
    .Y(_0516_)
  );
  sky130_fd_sc_hd__xor2_2 _1182_ (
    .A(_0511_),
    .B(_0516_),
    .X(_0517_)
  );
  sky130_fd_sc_hd__mux2_1 _1183_ (
    .A0(\hac_offset[12] ),
    .A1(_0517_),
    .S(phase_status[0]),
    .X(_0081_)
  );
  sky130_fd_sc_hd__nand2b_2 _1184_ (
    .A_N(\hac_inst.count[13] ),
    .B(link_rx[21]),
    .Y(_0518_)
  );
  sky130_fd_sc_hd__and2b_2 _1185_ (
    .A_N(link_rx[21]),
    .B(\hac_inst.count[13] ),
    .X(_0519_)
  );
  sky130_fd_sc_hd__inv_2 _1186_ (
    .A(_0519_),
    .Y(_0520_)
  );
  sky130_fd_sc_hd__nand2_2 _1187_ (
    .A(_0518_),
    .B(_0520_),
    .Y(_0521_)
  );
  sky130_fd_sc_hd__o21bai_2 _1188_ (
    .A1(_0511_),
    .A2(_0516_),
    .B1_N(_0510_),
    .Y(_0522_)
  );
  sky130_fd_sc_hd__xnor2_2 _1189_ (
    .A(_0521_),
    .B(_0522_),
    .Y(_0523_)
  );
  sky130_fd_sc_hd__mux2_1 _1190_ (
    .A0(\hac_offset[13] ),
    .A1(_0523_),
    .S(phase_status[0]),
    .X(_0082_)
  );
  sky130_fd_sc_hd__nand2b_2 _1191_ (
    .A_N(\hac_inst.count[14] ),
    .B(link_rx[22]),
    .Y(_0524_)
  );
  sky130_fd_sc_hd__nand2b_2 _1192_ (
    .A_N(link_rx[22]),
    .B(\hac_inst.count[14] ),
    .Y(_0525_)
  );
  sky130_fd_sc_hd__nand2_2 _1193_ (
    .A(_0524_),
    .B(_0525_),
    .Y(_0526_)
  );
  sky130_fd_sc_hd__a21oi_2 _1194_ (
    .A1(_0518_),
    .A2(_0522_),
    .B1(_0519_),
    .Y(_0527_)
  );
  sky130_fd_sc_hd__xor2_2 _1195_ (
    .A(_0526_),
    .B(_0527_),
    .X(_0528_)
  );
  sky130_fd_sc_hd__mux2_1 _1196_ (
    .A0(\hac_offset[14] ),
    .A1(_0528_),
    .S(phase_status[0]),
    .X(_0083_)
  );
  sky130_fd_sc_hd__and2b_2 _1197_ (
    .A_N(\hac_inst.count[15] ),
    .B(link_rx[23]),
    .X(_0529_)
  );
  sky130_fd_sc_hd__and2b_2 _1198_ (
    .A_N(link_rx[23]),
    .B(\hac_inst.count[15] ),
    .X(_0530_)
  );
  sky130_fd_sc_hd__or2_2 _1199_ (
    .A(_0529_),
    .B(_0530_),
    .X(_0531_)
  );
  sky130_fd_sc_hd__o21ai_2 _1200_ (
    .A1(_0526_),
    .A2(_0527_),
    .B1(_0525_),
    .Y(_0532_)
  );
  sky130_fd_sc_hd__xnor2_2 _1201_ (
    .A(_0531_),
    .B(_0532_),
    .Y(_0533_)
  );
  sky130_fd_sc_hd__mux2_1 _1202_ (
    .A0(\hac_offset[15] ),
    .A1(_0533_),
    .S(phase_status[0]),
    .X(_0084_)
  );
  sky130_fd_sc_hd__or2_2 _1203_ (
    .A(_0526_),
    .B(_0531_),
    .X(_0534_)
  );
  sky130_fd_sc_hd__or3_2 _1204_ (
    .A(_0511_),
    .B(_0521_),
    .C(_0534_),
    .X(_0535_)
  );
  sky130_fd_sc_hd__o21ba_2 _1205_ (
    .A1(_0525_),
    .A2(_0529_),
    .B1_N(_0530_),
    .X(_0536_)
  );
  sky130_fd_sc_hd__a21oi_2 _1206_ (
    .A1(_0510_),
    .A2(_0518_),
    .B1(_0519_),
    .Y(_0537_)
  );
  sky130_fd_sc_hd__or2_2 _1207_ (
    .A(_0534_),
    .B(_0537_),
    .X(_0538_)
  );
  sky130_fd_sc_hd__o211a_2 _1208_ (
    .A1(_0515_),
    .A2(_0535_),
    .B1(_0536_),
    .C1(_0538_),
    .X(_0539_)
  );
  sky130_fd_sc_hd__nand3b_2 _1209_ (
    .A_N(_0535_),
    .B(_0489_),
    .C(_0512_),
    .Y(_0540_)
  );
  sky130_fd_sc_hd__and2_2 _1210_ (
    .A(_0539_),
    .B(_0540_),
    .X(_0541_)
  );
  sky130_fd_sc_hd__and2b_2 _1211_ (
    .A_N(\hac_inst.count[16] ),
    .B(link_rx[24]),
    .X(_0542_)
  );
  sky130_fd_sc_hd__and2b_2 _1212_ (
    .A_N(link_rx[24]),
    .B(\hac_inst.count[16] ),
    .X(_0543_)
  );
  sky130_fd_sc_hd__or2_2 _1213_ (
    .A(_0542_),
    .B(_0543_),
    .X(_0544_)
  );
  sky130_fd_sc_hd__xor2_2 _1214_ (
    .A(_0541_),
    .B(_0544_),
    .X(_0545_)
  );
  sky130_fd_sc_hd__mux2_1 _1215_ (
    .A0(\hac_offset[16] ),
    .A1(_0545_),
    .S(phase_status[0]),
    .X(_0085_)
  );
  sky130_fd_sc_hd__and2b_2 _1216_ (
    .A_N(link_rx[25]),
    .B(\hac_inst.count[17] ),
    .X(_0546_)
  );
  sky130_fd_sc_hd__nand2b_2 _1217_ (
    .A_N(link_rx[25]),
    .B(\hac_inst.count[17] ),
    .Y(_0547_)
  );
  sky130_fd_sc_hd__and2b_2 _1218_ (
    .A_N(\hac_inst.count[17] ),
    .B(link_rx[25]),
    .X(_0548_)
  );
  sky130_fd_sc_hd__nor2_2 _1219_ (
    .A(_0546_),
    .B(_0548_),
    .Y(_0549_)
  );
  sky130_fd_sc_hd__o21ba_2 _1220_ (
    .A1(_0541_),
    .A2(_0544_),
    .B1_N(_0543_),
    .X(_0550_)
  );
  sky130_fd_sc_hd__xnor2_2 _1221_ (
    .A(_0549_),
    .B(_0550_),
    .Y(_0551_)
  );
  sky130_fd_sc_hd__mux2_1 _1222_ (
    .A0(\hac_offset[17] ),
    .A1(_0551_),
    .S(phase_status[0]),
    .X(_0086_)
  );
  sky130_fd_sc_hd__nand2b_2 _1223_ (
    .A_N(link_rx[26]),
    .B(\hac_inst.count[18] ),
    .Y(_0552_)
  );
  sky130_fd_sc_hd__xnor2_2 _1224_ (
    .A(\hac_inst.count[18] ),
    .B(link_rx[26]),
    .Y(_0553_)
  );
  sky130_fd_sc_hd__inv_2 _1225_ (
    .A(_0553_),
    .Y(_0554_)
  );
  sky130_fd_sc_hd__a21o_2 _1226_ (
    .A1(_0547_),
    .A2(_0550_),
    .B1(_0548_),
    .X(_0555_)
  );
  sky130_fd_sc_hd__xnor2_2 _1227_ (
    .A(_0553_),
    .B(_0555_),
    .Y(_0556_)
  );
  sky130_fd_sc_hd__mux2_1 _1228_ (
    .A0(\hac_offset[18] ),
    .A1(_0556_),
    .S(phase_status[0]),
    .X(_0087_)
  );
  sky130_fd_sc_hd__and2b_2 _1229_ (
    .A_N(\hac_inst.count[19] ),
    .B(link_rx[27]),
    .X(_0557_)
  );
  sky130_fd_sc_hd__and2b_2 _1230_ (
    .A_N(link_rx[27]),
    .B(\hac_inst.count[19] ),
    .X(_0558_)
  );
  sky130_fd_sc_hd__nor2_2 _1231_ (
    .A(_0557_),
    .B(_0558_),
    .Y(_0559_)
  );
  sky130_fd_sc_hd__o21a_2 _1232_ (
    .A1(_0554_),
    .A2(_0555_),
    .B1(_0552_),
    .X(_0560_)
  );
  sky130_fd_sc_hd__xnor2_2 _1233_ (
    .A(_0559_),
    .B(_0560_),
    .Y(_0561_)
  );
  sky130_fd_sc_hd__mux2_1 _1234_ (
    .A0(\hac_offset[19] ),
    .A1(_0561_),
    .S(phase_status[0]),
    .X(_0088_)
  );
  sky130_fd_sc_hd__and2b_2 _1235_ (
    .A_N(\hac_inst.count[20] ),
    .B(link_rx[28]),
    .X(_0562_)
  );
  sky130_fd_sc_hd__and2b_2 _1236_ (
    .A_N(link_rx[28]),
    .B(\hac_inst.count[20] ),
    .X(_0563_)
  );
  sky130_fd_sc_hd__nor2_2 _1237_ (
    .A(_0562_),
    .B(_0563_),
    .Y(_0564_)
  );
  sky130_fd_sc_hd__nand2b_2 _1238_ (
    .A_N(_0548_),
    .B(_0543_),
    .Y(_0565_)
  );
  sky130_fd_sc_hd__nand2_2 _1239_ (
    .A(_0553_),
    .B(_0559_),
    .Y(_0566_)
  );
  sky130_fd_sc_hd__a21oi_2 _1240_ (
    .A1(_0547_),
    .A2(_0565_),
    .B1(_0566_),
    .Y(_0567_)
  );
  sky130_fd_sc_hd__nor2_2 _1241_ (
    .A(_0552_),
    .B(_0557_),
    .Y(_0568_)
  );
  sky130_fd_sc_hd__or3_2 _1242_ (
    .A(_0558_),
    .B(_0567_),
    .C(_0568_),
    .X(_0569_)
  );
  sky130_fd_sc_hd__or4_2 _1243_ (
    .A(_0544_),
    .B(_0546_),
    .C(_0548_),
    .D(_0566_),
    .X(_0570_)
  );
  sky130_fd_sc_hd__nor2_2 _1244_ (
    .A(_0541_),
    .B(_0570_),
    .Y(_0571_)
  );
  sky130_fd_sc_hd__a21o_2 _1245_ (
    .A1(_0539_),
    .A2(_0540_),
    .B1(_0570_),
    .X(_0572_)
  );
  sky130_fd_sc_hd__o21a_2 _1246_ (
    .A1(_0569_),
    .A2(_0571_),
    .B1(_0564_),
    .X(_0573_)
  );
  sky130_fd_sc_hd__nor3_2 _1247_ (
    .A(_0564_),
    .B(_0569_),
    .C(_0571_),
    .Y(_0574_)
  );
  sky130_fd_sc_hd__nor2_2 _1248_ (
    .A(_0573_),
    .B(_0574_),
    .Y(_0575_)
  );
  sky130_fd_sc_hd__mux2_1 _1249_ (
    .A0(\hac_offset[20] ),
    .A1(_0575_),
    .S(phase_status[0]),
    .X(_0089_)
  );
  sky130_fd_sc_hd__and2b_2 _1250_ (
    .A_N(\hac_inst.count[21] ),
    .B(link_rx[29]),
    .X(_0576_)
  );
  sky130_fd_sc_hd__and2b_2 _1251_ (
    .A_N(link_rx[29]),
    .B(\hac_inst.count[21] ),
    .X(_0577_)
  );
  sky130_fd_sc_hd__nor2_2 _1252_ (
    .A(_0576_),
    .B(_0577_),
    .Y(_0578_)
  );
  sky130_fd_sc_hd__o21ai_2 _1253_ (
    .A1(_0563_),
    .A2(_0573_),
    .B1(_0578_),
    .Y(_0579_)
  );
  sky130_fd_sc_hd__o31a_2 _1254_ (
    .A1(_0563_),
    .A2(_0573_),
    .A3(_0578_),
    .B1(phase_status[0]),
    .X(_0580_)
  );
  sky130_fd_sc_hd__a22o_2 _1255_ (
    .A1(_0102_),
    .A2(\hac_offset[21] ),
    .B1(_0579_),
    .B2(_0580_),
    .X(_0090_)
  );
  sky130_fd_sc_hd__xor2_2 _1256_ (
    .A(\hac_inst.count[22] ),
    .B(link_rx[30]),
    .X(_0581_)
  );
  sky130_fd_sc_hd__or2_2 _1257_ (
    .A(_0563_),
    .B(_0577_),
    .X(_0582_)
  );
  sky130_fd_sc_hd__nor2_2 _1258_ (
    .A(_0573_),
    .B(_0582_),
    .Y(_0583_)
  );
  sky130_fd_sc_hd__and2b_2 _1259_ (
    .A_N(_0576_),
    .B(_0582_),
    .X(_0584_)
  );
  sky130_fd_sc_hd__nor2_2 _1260_ (
    .A(_0576_),
    .B(_0583_),
    .Y(_0585_)
  );
  sky130_fd_sc_hd__xnor2_2 _1261_ (
    .A(_0581_),
    .B(_0585_),
    .Y(_0586_)
  );
  sky130_fd_sc_hd__mux2_1 _1262_ (
    .A0(\hac_offset[22] ),
    .A1(_0586_),
    .S(phase_status[0]),
    .X(_0091_)
  );
  sky130_fd_sc_hd__xor2_2 _1263_ (
    .A(\hac_inst.count[23] ),
    .B(link_rx[31]),
    .X(_0587_)
  );
  sky130_fd_sc_hd__o32a_2 _1264_ (
    .A1(_0576_),
    .A2(_0581_),
    .A3(_0583_),
    .B1(link_rx[30]),
    .B2(_0105_),
    .X(_0588_)
  );
  sky130_fd_sc_hd__xor2_2 _1265_ (
    .A(_0587_),
    .B(_0588_),
    .X(_0589_)
  );
  sky130_fd_sc_hd__mux2_1 _1266_ (
    .A0(\hac_offset[23] ),
    .A1(_0589_),
    .S(phase_status[0]),
    .X(_0092_)
  );
  sky130_fd_sc_hd__xor2_2 _1267_ (
    .A(\hac_inst.count[24] ),
    .B(link_rx[32]),
    .X(_0590_)
  );
  sky130_fd_sc_hd__nor2_2 _1268_ (
    .A(_0581_),
    .B(_0587_),
    .Y(_0591_)
  );
  sky130_fd_sc_hd__o211a_2 _1269_ (
    .A1(\hac_inst.count[23] ),
    .A2(_0120_),
    .B1(_0119_),
    .C1(\hac_inst.count[22] ),
    .X(_0592_)
  );
  sky130_fd_sc_hd__a221o_2 _1270_ (
    .A1(\hac_inst.count[23] ),
    .A2(_0120_),
    .B1(_0584_),
    .B2(_0591_),
    .C1(_0592_),
    .X(_0593_)
  );
  sky130_fd_sc_hd__a31oi_2 _1271_ (
    .A1(_0564_),
    .A2(_0578_),
    .A3(_0591_),
    .B1(_0593_),
    .Y(_0594_)
  );
  sky130_fd_sc_hd__nor2_2 _1272_ (
    .A(_0569_),
    .B(_0593_),
    .Y(_0595_)
  );
  sky130_fd_sc_hd__a21oi_2 _1273_ (
    .A1(_0572_),
    .A2(_0595_),
    .B1(_0594_),
    .Y(_0596_)
  );
  sky130_fd_sc_hd__nand2b_2 _1274_ (
    .A_N(_0590_),
    .B(_0596_),
    .Y(_0597_)
  );
  sky130_fd_sc_hd__xnor2_2 _1275_ (
    .A(_0590_),
    .B(_0596_),
    .Y(_0598_)
  );
  sky130_fd_sc_hd__mux2_1 _1276_ (
    .A0(\hac_offset[24] ),
    .A1(_0598_),
    .S(phase_status[0]),
    .X(_0093_)
  );
  sky130_fd_sc_hd__a21bo_2 _1277_ (
    .A1(\hac_inst.count[24] ),
    .A2(_0121_),
    .B1_N(_0597_),
    .X(_0599_)
  );
  sky130_fd_sc_hd__and2b_2 _1278_ (
    .A_N(link_rx[33]),
    .B(\hac_inst.count[25] ),
    .X(_0600_)
  );
  sky130_fd_sc_hd__and2b_2 _1279_ (
    .A_N(\hac_inst.count[25] ),
    .B(link_rx[33]),
    .X(_0601_)
  );
  sky130_fd_sc_hd__or2_2 _1280_ (
    .A(_0600_),
    .B(_0601_),
    .X(_0602_)
  );
  sky130_fd_sc_hd__xnor2_2 _1281_ (
    .A(_0599_),
    .B(_0602_),
    .Y(_0603_)
  );
  sky130_fd_sc_hd__mux2_1 _1282_ (
    .A0(\hac_offset[25] ),
    .A1(_0603_),
    .S(phase_status[0]),
    .X(_0094_)
  );
  sky130_fd_sc_hd__xor2_2 _1283_ (
    .A(\hac_inst.count[26] ),
    .B(link_rx[34]),
    .X(_0604_)
  );
  sky130_fd_sc_hd__a21oi_2 _1284_ (
    .A1(\hac_inst.count[24] ),
    .A2(_0121_),
    .B1(_0600_),
    .Y(_0605_)
  );
  sky130_fd_sc_hd__nor2_2 _1285_ (
    .A(_0599_),
    .B(_0600_),
    .Y(_0606_)
  );
  sky130_fd_sc_hd__nor2_2 _1286_ (
    .A(_0601_),
    .B(_0606_),
    .Y(_0607_)
  );
  sky130_fd_sc_hd__xnor2_2 _1287_ (
    .A(_0604_),
    .B(_0607_),
    .Y(_0608_)
  );
  sky130_fd_sc_hd__mux2_1 _1288_ (
    .A0(\hac_offset[26] ),
    .A1(_0608_),
    .S(phase_status[0]),
    .X(_0095_)
  );
  sky130_fd_sc_hd__and2b_2 _1289_ (
    .A_N(\hac_inst.count[27] ),
    .B(link_rx[35]),
    .X(_0609_)
  );
  sky130_fd_sc_hd__and2b_2 _1290_ (
    .A_N(link_rx[35]),
    .B(\hac_inst.count[27] ),
    .X(_0610_)
  );
  sky130_fd_sc_hd__inv_2 _1291_ (
    .A(_0610_),
    .Y(_0611_)
  );
  sky130_fd_sc_hd__or2_2 _1292_ (
    .A(_0609_),
    .B(_0610_),
    .X(_0612_)
  );
  sky130_fd_sc_hd__o32a_2 _1293_ (
    .A1(_0601_),
    .A2(_0604_),
    .A3(_0606_),
    .B1(link_rx[34]),
    .B2(_0112_),
    .X(_0613_)
  );
  sky130_fd_sc_hd__xor2_2 _1294_ (
    .A(_0612_),
    .B(_0613_),
    .X(_0614_)
  );
  sky130_fd_sc_hd__mux2_1 _1295_ (
    .A0(\hac_offset[27] ),
    .A1(_0614_),
    .S(phase_status[0]),
    .X(_0096_)
  );
  sky130_fd_sc_hd__or2_2 _1296_ (
    .A(_0604_),
    .B(_0612_),
    .X(_0615_)
  );
  sky130_fd_sc_hd__or3_2 _1297_ (
    .A(_0590_),
    .B(_0602_),
    .C(_0615_),
    .X(_0616_)
  );
  sky130_fd_sc_hd__a211o_2 _1298_ (
    .A1(_0572_),
    .A2(_0595_),
    .B1(_0616_),
    .C1(_0594_),
    .X(_0617_)
  );
  sky130_fd_sc_hd__or3_2 _1299_ (
    .A(_0601_),
    .B(_0605_),
    .C(_0615_),
    .X(_0618_)
  );
  sky130_fd_sc_hd__o311a_2 _1300_ (
    .A1(_0112_),
    .A2(link_rx[34]),
    .A3(_0609_),
    .B1(_0611_),
    .C1(_0618_),
    .X(_0619_)
  );
  sky130_fd_sc_hd__xor2_2 _1301_ (
    .A(\hac_inst.count[28] ),
    .B(link_rx[36]),
    .X(_0620_)
  );
  sky130_fd_sc_hd__a21oi_2 _1302_ (
    .A1(_0617_),
    .A2(_0619_),
    .B1(_0620_),
    .Y(_0621_)
  );
  sky130_fd_sc_hd__and3_2 _1303_ (
    .A(_0617_),
    .B(_0619_),
    .C(_0620_),
    .X(_0622_)
  );
  sky130_fd_sc_hd__nand2_2 _1304_ (
    .A(_0102_),
    .B(\hac_offset[28] ),
    .Y(_0623_)
  );
  sky130_fd_sc_hd__o31ai_2 _1305_ (
    .A1(_0102_),
    .A2(_0621_),
    .A3(_0622_),
    .B1(_0623_),
    .Y(_0097_)
  );
  sky130_fd_sc_hd__and2b_2 _1306_ (
    .A_N(\hac_inst.count[29] ),
    .B(link_rx[37]),
    .X(_0624_)
  );
  sky130_fd_sc_hd__nand2b_2 _1307_ (
    .A_N(link_rx[37]),
    .B(\hac_inst.count[29] ),
    .Y(_0625_)
  );
  sky130_fd_sc_hd__and2b_2 _1308_ (
    .A_N(_0624_),
    .B(_0625_),
    .X(_0626_)
  );
  sky130_fd_sc_hd__a21oi_2 _1309_ (
    .A1(\hac_inst.count[28] ),
    .A2(_0122_),
    .B1(_0621_),
    .Y(_0627_)
  );
  sky130_fd_sc_hd__xnor2_2 _1310_ (
    .A(_0626_),
    .B(_0627_),
    .Y(_0628_)
  );
  sky130_fd_sc_hd__mux2_1 _1311_ (
    .A0(\hac_offset[29] ),
    .A1(_0628_),
    .S(phase_status[0]),
    .X(_0098_)
  );
  sky130_fd_sc_hd__xor2_2 _1312_ (
    .A(\hac_inst.count[30] ),
    .B(link_rx[38]),
    .X(_0629_)
  );
  sky130_fd_sc_hd__a21o_2 _1313_ (
    .A1(_0625_),
    .A2(_0627_),
    .B1(_0624_),
    .X(_0630_)
  );
  sky130_fd_sc_hd__a211o_2 _1314_ (
    .A1(_0625_),
    .A2(_0627_),
    .B1(_0629_),
    .C1(_0624_),
    .X(_0631_)
  );
  sky130_fd_sc_hd__nand2_2 _1315_ (
    .A(_0629_),
    .B(_0630_),
    .Y(_0632_)
  );
  sky130_fd_sc_hd__and2_2 _1316_ (
    .A(_0102_),
    .B(\hac_offset[30] ),
    .X(_0633_)
  );
  sky130_fd_sc_hd__a31o_2 _1317_ (
    .A1(phase_status[0]),
    .A2(_0631_),
    .A3(_0632_),
    .B1(_0633_),
    .X(_0099_)
  );
  sky130_fd_sc_hd__o21ai_2 _1318_ (
    .A1(_0115_),
    .A2(link_rx[38]),
    .B1(_0631_),
    .Y(_0634_)
  );
  sky130_fd_sc_hd__xor2_2 _1319_ (
    .A(\hac_inst.count[31] ),
    .B(link_rx[39]),
    .X(_0635_)
  );
  sky130_fd_sc_hd__xnor2_2 _1320_ (
    .A(_0634_),
    .B(_0635_),
    .Y(_0636_)
  );
  sky130_fd_sc_hd__mux2_1 _1321_ (
    .A0(\hac_offset[31] ),
    .A1(_0636_),
    .S(phase_status[0]),
    .X(_0100_)
  );
  sky130_fd_sc_hd__dfrtp_2 _1322_ (
    .CLK(clk),
    .D(_0034_),
    .Q(sac_val[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1323_ (
    .CLK(clk),
    .D(_0035_),
    .Q(sac_val[1]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1324_ (
    .CLK(clk),
    .D(_0036_),
    .Q(sac_val[2]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1325_ (
    .CLK(clk),
    .D(_0037_),
    .Q(sac_val[3]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1326_ (
    .CLK(clk),
    .D(_0038_),
    .Q(sac_val[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1327_ (
    .CLK(clk),
    .D(_0039_),
    .Q(sac_val[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1328_ (
    .CLK(clk),
    .D(_0040_),
    .Q(sac_val[6]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1329_ (
    .CLK(clk),
    .D(_0041_),
    .Q(sac_val[7]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1330_ (
    .CLK(clk),
    .D(_0042_),
    .Q(sac_val[8]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1331_ (
    .CLK(clk),
    .D(_0043_),
    .Q(sac_val[9]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1332_ (
    .CLK(clk),
    .D(_0044_),
    .Q(sac_val[10]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1333_ (
    .CLK(clk),
    .D(_0045_),
    .Q(sac_val[11]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1334_ (
    .CLK(clk),
    .D(_0046_),
    .Q(sac_val[12]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1335_ (
    .CLK(clk),
    .D(_0047_),
    .Q(sac_val[13]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1336_ (
    .CLK(clk),
    .D(_0048_),
    .Q(sac_val[14]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1337_ (
    .CLK(clk),
    .D(_0049_),
    .Q(sac_val[15]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1338_ (
    .CLK(clk),
    .D(_0050_),
    .Q(sac_val[16]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1339_ (
    .CLK(clk),
    .D(_0051_),
    .Q(sac_val[17]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1340_ (
    .CLK(clk),
    .D(_0052_),
    .Q(sac_val[18]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1341_ (
    .CLK(clk),
    .D(_0053_),
    .Q(sac_val[19]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1342_ (
    .CLK(clk),
    .D(_0054_),
    .Q(sac_val[20]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1343_ (
    .CLK(clk),
    .D(_0055_),
    .Q(sac_val[21]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1344_ (
    .CLK(clk),
    .D(_0056_),
    .Q(sac_val[22]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1345_ (
    .CLK(clk),
    .D(_0057_),
    .Q(sac_val[23]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1346_ (
    .CLK(clk),
    .D(_0058_),
    .Q(sac_val[24]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1347_ (
    .CLK(clk),
    .D(_0059_),
    .Q(sac_val[25]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1348_ (
    .CLK(clk),
    .D(_0060_),
    .Q(sac_val[26]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1349_ (
    .CLK(clk),
    .D(_0061_),
    .Q(sac_val[27]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1350_ (
    .CLK(clk),
    .D(_0062_),
    .Q(sac_val[28]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1351_ (
    .CLK(clk),
    .D(_0063_),
    .Q(sac_val[29]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1352_ (
    .CLK(clk),
    .D(_0064_),
    .Q(sac_val[30]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1353_ (
    .CLK(clk),
    .D(_0065_),
    .Q(sac_val[31]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1354_ (
    .CLK(clk),
    .D(_0066_),
    .Q(phase_status[0]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1355_ (
    .CLK(clk),
    .D(_0067_),
    .Q(phase_status[4]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1356_ (
    .CLK(clk),
    .D(_0068_),
    .Q(phase_status[5]),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1357_ (
    .CLK(clk),
    .D(_0069_),
    .Q(\hac_offset[0] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1358_ (
    .CLK(clk),
    .D(_0070_),
    .Q(\hac_offset[1] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1359_ (
    .CLK(clk),
    .D(_0071_),
    .Q(\hac_offset[2] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1360_ (
    .CLK(clk),
    .D(_0072_),
    .Q(\hac_offset[3] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1361_ (
    .CLK(clk),
    .D(_0073_),
    .Q(\hac_offset[4] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1362_ (
    .CLK(clk),
    .D(_0074_),
    .Q(\hac_offset[5] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1363_ (
    .CLK(clk),
    .D(_0075_),
    .Q(\hac_offset[6] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1364_ (
    .CLK(clk),
    .D(_0076_),
    .Q(\hac_offset[7] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1365_ (
    .CLK(clk),
    .D(_0077_),
    .Q(\hac_offset[8] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1366_ (
    .CLK(clk),
    .D(_0078_),
    .Q(\hac_offset[9] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1367_ (
    .CLK(clk),
    .D(_0079_),
    .Q(\hac_offset[10] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1368_ (
    .CLK(clk),
    .D(_0080_),
    .Q(\hac_offset[11] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1369_ (
    .CLK(clk),
    .D(_0081_),
    .Q(\hac_offset[12] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1370_ (
    .CLK(clk),
    .D(_0082_),
    .Q(\hac_offset[13] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1371_ (
    .CLK(clk),
    .D(_0083_),
    .Q(\hac_offset[14] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1372_ (
    .CLK(clk),
    .D(_0084_),
    .Q(\hac_offset[15] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1373_ (
    .CLK(clk),
    .D(_0085_),
    .Q(\hac_offset[16] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1374_ (
    .CLK(clk),
    .D(_0086_),
    .Q(\hac_offset[17] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1375_ (
    .CLK(clk),
    .D(_0087_),
    .Q(\hac_offset[18] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1376_ (
    .CLK(clk),
    .D(_0088_),
    .Q(\hac_offset[19] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1377_ (
    .CLK(clk),
    .D(_0089_),
    .Q(\hac_offset[20] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1378_ (
    .CLK(clk),
    .D(_0090_),
    .Q(\hac_offset[21] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1379_ (
    .CLK(clk),
    .D(_0091_),
    .Q(\hac_offset[22] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1380_ (
    .CLK(clk),
    .D(_0092_),
    .Q(\hac_offset[23] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1381_ (
    .CLK(clk),
    .D(_0093_),
    .Q(\hac_offset[24] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1382_ (
    .CLK(clk),
    .D(_0094_),
    .Q(\hac_offset[25] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1383_ (
    .CLK(clk),
    .D(_0095_),
    .Q(\hac_offset[26] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1384_ (
    .CLK(clk),
    .D(_0096_),
    .Q(\hac_offset[27] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1385_ (
    .CLK(clk),
    .D(_0097_),
    .Q(\hac_offset[28] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1386_ (
    .CLK(clk),
    .D(_0098_),
    .Q(\hac_offset[29] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1387_ (
    .CLK(clk),
    .D(_0099_),
    .Q(\hac_offset[30] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1388_ (
    .CLK(clk),
    .D(_0100_),
    .Q(\hac_offset[31] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _1389_ (
    .CLK(clk),
    .D(_0001_),
    .Q(link_rx_r),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _1390_ (
    .CLK(clk),
    .D(_0000_),
    .Q(instr_ready),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1391_ (
    .CLK(clk),
    .D(_0002_),
    .Q(\hac_inst.count[0] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1392_ (
    .CLK(clk),
    .D(_0013_),
    .Q(\hac_inst.count[1] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1393_ (
    .CLK(clk),
    .D(_0024_),
    .Q(\hac_inst.count[2] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _1394_ (
    .CLK(clk),
    .D(_0027_),
    .Q(\hac_inst.count[3] ),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1395_ (
    .CLK(clk),
    .D(_0028_),
    .Q(\hac_inst.count[4] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _1396_ (
    .CLK(clk),
    .D(_0029_),
    .Q(\hac_inst.count[5] ),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _1397_ (
    .CLK(clk),
    .D(_0030_),
    .Q(\hac_inst.count[6] ),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _1398_ (
    .CLK(clk),
    .D(_0031_),
    .Q(\hac_inst.count[7] ),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _1399_ (
    .CLK(clk),
    .D(_0032_),
    .Q(\hac_inst.count[8] ),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfstp_2 _1400_ (
    .CLK(clk),
    .D(_0033_),
    .Q(\hac_inst.count[9] ),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1401_ (
    .CLK(clk),
    .D(_0003_),
    .Q(\hac_inst.count[10] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1402_ (
    .CLK(clk),
    .D(_0004_),
    .Q(\hac_inst.count[11] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1403_ (
    .CLK(clk),
    .D(_0005_),
    .Q(\hac_inst.count[12] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1404_ (
    .CLK(clk),
    .D(_0006_),
    .Q(\hac_inst.count[13] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1405_ (
    .CLK(clk),
    .D(_0007_),
    .Q(\hac_inst.count[14] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1406_ (
    .CLK(clk),
    .D(_0008_),
    .Q(\hac_inst.count[15] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1407_ (
    .CLK(clk),
    .D(_0009_),
    .Q(\hac_inst.count[16] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1408_ (
    .CLK(clk),
    .D(_0010_),
    .Q(\hac_inst.count[17] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1409_ (
    .CLK(clk),
    .D(_0011_),
    .Q(\hac_inst.count[18] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1410_ (
    .CLK(clk),
    .D(_0012_),
    .Q(\hac_inst.count[19] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1411_ (
    .CLK(clk),
    .D(_0014_),
    .Q(\hac_inst.count[20] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1412_ (
    .CLK(clk),
    .D(_0015_),
    .Q(\hac_inst.count[21] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1413_ (
    .CLK(clk),
    .D(_0016_),
    .Q(\hac_inst.count[22] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1414_ (
    .CLK(clk),
    .D(_0017_),
    .Q(\hac_inst.count[23] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1415_ (
    .CLK(clk),
    .D(_0018_),
    .Q(\hac_inst.count[24] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1416_ (
    .CLK(clk),
    .D(_0019_),
    .Q(\hac_inst.count[25] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1417_ (
    .CLK(clk),
    .D(_0020_),
    .Q(\hac_inst.count[26] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1418_ (
    .CLK(clk),
    .D(_0021_),
    .Q(\hac_inst.count[27] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1419_ (
    .CLK(clk),
    .D(_0022_),
    .Q(\hac_inst.count[28] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1420_ (
    .CLK(clk),
    .D(_0023_),
    .Q(\hac_inst.count[29] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1421_ (
    .CLK(clk),
    .D(_0025_),
    .Q(\hac_inst.count[30] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_2 _1422_ (
    .CLK(clk),
    .D(_0026_),
    .Q(\hac_inst.count[31] ),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__conb_1 _1423_ (
    .HI(phase_status[2])
  );
  sky130_fd_sc_hd__conb_1 _1424_ (
    .LO(link_tx[0])
  );
  sky130_fd_sc_hd__conb_1 _1425_ (
    .LO(link_tx[1])
  );
  sky130_fd_sc_hd__conb_1 _1426_ (
    .LO(link_tx[2])
  );
  sky130_fd_sc_hd__conb_1 _1427_ (
    .LO(link_tx[3])
  );
  sky130_fd_sc_hd__conb_1 _1428_ (
    .LO(link_tx[4])
  );
  sky130_fd_sc_hd__conb_1 _1429_ (
    .LO(link_tx[5])
  );
  sky130_fd_sc_hd__conb_1 _1430_ (
    .LO(link_tx[6])
  );
  sky130_fd_sc_hd__conb_1 _1431_ (
    .LO(link_tx[7])
  );
  sky130_fd_sc_hd__conb_1 _1432_ (
    .LO(link_tx[8])
  );
  sky130_fd_sc_hd__conb_1 _1433_ (
    .LO(link_tx[9])
  );
  sky130_fd_sc_hd__conb_1 _1434_ (
    .LO(link_tx[10])
  );
  sky130_fd_sc_hd__conb_1 _1435_ (
    .LO(link_tx[11])
  );
  sky130_fd_sc_hd__conb_1 _1436_ (
    .LO(link_tx[12])
  );
  sky130_fd_sc_hd__conb_1 _1437_ (
    .LO(link_tx[13])
  );
  sky130_fd_sc_hd__conb_1 _1438_ (
    .LO(link_tx[14])
  );
  sky130_fd_sc_hd__conb_1 _1439_ (
    .LO(link_tx[15])
  );
  sky130_fd_sc_hd__conb_1 _1440_ (
    .LO(link_tx[16])
  );
  sky130_fd_sc_hd__conb_1 _1441_ (
    .LO(link_tx[17])
  );
  sky130_fd_sc_hd__conb_1 _1442_ (
    .LO(link_tx[18])
  );
  sky130_fd_sc_hd__conb_1 _1443_ (
    .LO(link_tx[19])
  );
  sky130_fd_sc_hd__conb_1 _1444_ (
    .LO(link_tx[20])
  );
  sky130_fd_sc_hd__conb_1 _1445_ (
    .LO(link_tx[21])
  );
  sky130_fd_sc_hd__conb_1 _1446_ (
    .LO(link_tx[22])
  );
  sky130_fd_sc_hd__conb_1 _1447_ (
    .LO(link_tx[23])
  );
  sky130_fd_sc_hd__conb_1 _1448_ (
    .LO(link_tx[24])
  );
  sky130_fd_sc_hd__conb_1 _1449_ (
    .LO(link_tx[25])
  );
  sky130_fd_sc_hd__conb_1 _1450_ (
    .LO(link_tx[26])
  );
  sky130_fd_sc_hd__conb_1 _1451_ (
    .LO(link_tx[27])
  );
  sky130_fd_sc_hd__conb_1 _1452_ (
    .LO(link_tx[28])
  );
  sky130_fd_sc_hd__conb_1 _1453_ (
    .LO(link_tx[29])
  );
  sky130_fd_sc_hd__conb_1 _1454_ (
    .LO(link_tx[30])
  );
  sky130_fd_sc_hd__conb_1 _1455_ (
    .LO(link_tx[31])
  );
  sky130_fd_sc_hd__conb_1 _1456_ (
    .LO(link_tx[32])
  );
  sky130_fd_sc_hd__conb_1 _1457_ (
    .LO(link_tx[33])
  );
  sky130_fd_sc_hd__conb_1 _1458_ (
    .LO(link_tx[34])
  );
  sky130_fd_sc_hd__conb_1 _1459_ (
    .LO(link_tx[35])
  );
  sky130_fd_sc_hd__conb_1 _1460_ (
    .LO(link_tx[36])
  );
  sky130_fd_sc_hd__conb_1 _1461_ (
    .LO(link_tx[37])
  );
  sky130_fd_sc_hd__conb_1 _1462_ (
    .LO(link_tx[38])
  );
  sky130_fd_sc_hd__conb_1 _1463_ (
    .LO(link_tx[39])
  );
  sky130_fd_sc_hd__conb_1 _1464_ (
    .LO(link_tx[40])
  );
  sky130_fd_sc_hd__conb_1 _1465_ (
    .LO(link_tx[41])
  );
  sky130_fd_sc_hd__conb_1 _1466_ (
    .LO(link_tx[42])
  );
  sky130_fd_sc_hd__conb_1 _1467_ (
    .LO(link_tx[43])
  );
  sky130_fd_sc_hd__conb_1 _1468_ (
    .LO(link_tx[44])
  );
  sky130_fd_sc_hd__conb_1 _1469_ (
    .LO(link_tx[45])
  );
  sky130_fd_sc_hd__conb_1 _1470_ (
    .LO(link_tx[46])
  );
  sky130_fd_sc_hd__conb_1 _1471_ (
    .LO(link_tx[47])
  );
  sky130_fd_sc_hd__conb_1 _1472_ (
    .LO(link_tx_v)
  );
  sky130_fd_sc_hd__conb_1 _1473_ (
    .LO(phase_status[1])
  );
  sky130_fd_sc_hd__conb_1 _1474_ (
    .LO(phase_status[3])
  );
  sky130_fd_sc_hd__conb_1 _1475_ (
    .LO(phase_status[6])
  );
  sky130_fd_sc_hd__conb_1 _1476_ (
    .LO(phase_status[7])
  );
endmodule
